import type {
  Asset,
  AssetId,
  Interaction,
  Scenario,
  ScenarioId,
  ShockMap,
} from "./types";

export const AS_OF = "2026-08-18";
export const AS_OF_LABEL = "18 Aug 2026";

export const ASSETS: Asset[] = [
  { id: "AAPL", ticker: "AAPL", name: "Apple", class: "equity", last: 306.7, kind: "usd", mu: 0.11, sigma: 0.24, colorVar: "var(--color-aapl)" },
  { id: "MSFT", ticker: "MSFT", name: "Microsoft", class: "equity", last: 478.16, kind: "usd", mu: 0.13, sigma: 0.23, colorVar: "var(--color-msft)" },
  { id: "NVDA", ticker: "NVDA", name: "NVIDIA", class: "equity", last: 220.07, kind: "usd", mu: 0.22, sigma: 0.42, colorVar: "var(--color-nvda)" },
  { id: "TSLA", ticker: "TSLA", name: "Tesla", class: "equity", last: 332.59, kind: "usd", mu: 0.14, sigma: 0.52, colorVar: "var(--color-tsla)" },
  { id: "ASML", ticker: "ASML", name: "ASML", class: "equity", last: 1788, kind: "usd", mu: 0.16, sigma: 0.38, colorVar: "var(--color-asml)" },
  { id: "RHM", ticker: "RHM", name: "Rheinmetall", class: "equity", last: 1214, kind: "usd", mu: 0.1, sigma: 0.44, colorVar: "var(--color-rhm)" },
  { id: "LLY", ticker: "LLY", name: "Eli Lilly", class: "equity", last: 1215, kind: "usd", mu: 0.12, sigma: 0.32, colorVar: "var(--color-lly)" },
  { id: "MSTR", ticker: "MSTR", name: "Strategy", class: "equity", last: 94, kind: "usd", mu: 0.2, sigma: 0.82, colorVar: "var(--color-mstr)" },
  { id: "CCJ", ticker: "CCJ", name: "Cameco", class: "equity", last: 95.5, kind: "usd", mu: 0.13, sigma: 0.48, colorVar: "var(--color-ccj)" },
  { id: "SPX", ticker: "SPX", name: "S&P 500", class: "etf", last: 7730, kind: "index", mu: 0.08, sigma: 0.16, colorVar: "var(--color-spx)" },
  { id: "URTH", ticker: "URTH", name: "MSCI World", class: "etf", last: 208.4, kind: "usd", mu: 0.07, sigma: 0.15, colorVar: "var(--color-urth)" },
  { id: "QQQ", ticker: "QQQ", name: "Nasdaq 100", class: "etf", last: 628.2, kind: "usd", mu: 0.12, sigma: 0.22, colorVar: "var(--color-qqq)" },
  { id: "TLT", ticker: "TLT", name: "20Y Treasury", class: "etf", last: 88.6, kind: "usd", mu: 0.02, sigma: 0.14, colorVar: "var(--color-tlt)" },
  { id: "SMH", ticker: "SMH", name: "VanEck Semi", class: "etf", last: 312, kind: "usd", mu: 0.16, sigma: 0.34, colorVar: "var(--color-smh)" },
  { id: "ARKK", ticker: "ARKK", name: "ARK Innovation", class: "etf", last: 54.2, kind: "usd", mu: 0.08, sigma: 0.48, colorVar: "var(--color-arkk)" },
  { id: "BOTZ", ticker: "BOTZ", name: "Robotics & AI", class: "etf", last: 35.4, kind: "usd", mu: 0.11, sigma: 0.3, colorVar: "var(--color-botz)" },
  { id: "IGLN", ticker: "IGLN", name: "Physical Gold", class: "etf", last: 85.18, kind: "usd", mu: 0.04, sigma: 0.16, colorVar: "var(--color-igln)" },
  { id: "VNQ", ticker: "VNQ", name: "US Real Estate", class: "etf", last: 97.98, kind: "usd", mu: 0.06, sigma: 0.2, colorVar: "var(--color-vnq)" },
  { id: "PIMIX", ticker: "PIMIX", name: "PIMCO Income", class: "fund", last: 10.73, kind: "usd", mu: 0.045, sigma: 0.06, colorVar: "var(--color-pimix)" },
  { id: "FVST", ticker: "FVST", name: "FvS Multi Opp", class: "fund", last: 199.4, kind: "usd", mu: 0.06, sigma: 0.1, colorVar: "var(--color-fvst)" },
  { id: "BTC", ticker: "BTC", name: "Bitcoin", class: "crypto", last: 64755, kind: "crypto", mu: 0.18, sigma: 0.58, colorVar: "var(--color-btc)" },
  { id: "ETH", ticker: "ETH", name: "Ethereum", class: "crypto", last: 1916, kind: "crypto", mu: 0.16, sigma: 0.66, colorVar: "var(--color-eth)" },
  { id: "XRP", ticker: "XRP", name: "Ripple", class: "crypto", last: 1.001, kind: "crypto", mu: 0.1, sigma: 0.72, colorVar: "var(--color-xrp)" },
  { id: "SOL", ticker: "SOL", name: "Solana", class: "crypto", last: 76.95, kind: "crypto", mu: 0.2, sigma: 0.78, colorVar: "var(--color-sol)" },
  { id: "LINK", ticker: "LINK", name: "Chainlink", class: "crypto", last: 9.48, kind: "crypto", mu: 0.14, sigma: 0.74, colorVar: "var(--color-link)" },
  { id: "RENDER", ticker: "RENDER", name: "Render", class: "crypto", last: 1.27, kind: "crypto", mu: 0.18, sigma: 0.88, colorVar: "var(--color-render)" },
  { id: "TAO", ticker: "TAO", name: "Bittensor", class: "crypto", last: 192, kind: "crypto", mu: 0.22, sigma: 0.92, colorVar: "var(--color-tao)" },
  { id: "XMR", ticker: "XMR", name: "Monero", class: "crypto", last: 415, kind: "crypto", mu: 0.08, sigma: 0.7, colorVar: "var(--color-xmr)" },
  { id: "UNI", ticker: "UNI", name: "Uniswap", class: "crypto", last: 3.28, kind: "crypto", mu: 0.12, sigma: 0.8, colorVar: "var(--color-uni)" },
  { id: "DOGE", ticker: "DOGE", name: "Dogecoin", class: "crypto", last: 0.0701, kind: "crypto", mu: 0.05, sigma: 0.95, colorVar: "var(--color-doge)" },
];

export const ASSET_BY_ID: Record<AssetId, Asset> = Object.fromEntries(
  ASSETS.map((a) => [a.id, a]),
) as Record<AssetId, Asset>;

export const ASSET_IDS = ASSETS.map((a) => a.id);

export const TECH: AssetId[] = ["AAPL", "MSFT", "NVDA", "TSLA", "ASML", "QQQ", "SMH", "ARKK", "BOTZ"];
export const CRYPTO: AssetId[] = ["BTC", "ETH", "XRP", "SOL", "LINK", "RENDER", "TAO", "XMR", "UNI", "DOGE"];
export const HARDWARE: AssetId[] = ["NVDA", "ASML", "SMH", "AAPL", "TSLA"];
export const SEMI: AssetId[] = ["NVDA", "ASML", "SMH"];
export const GOLD: AssetId[] = ["IGLN"];
export const DURATION: AssetId[] = ["TLT", "PIMIX"];
export const AI_DECENTRAL: AssetId[] = ["TAO", "RENDER"];

function fill(spec: Partial<ShockMap>, fallback = 0): ShockMap {
  const out = {} as ShockMap;
  for (const id of ASSET_IDS) out[id] = spec[id] ?? fallback;
  return out;
}

function S(rows: Array<[AssetId | readonly AssetId[], number]>, fallback = 0): ShockMap {
  const spec: Partial<ShockMap> = {};
  for (const [keys, v] of rows) {
    if (typeof keys === "string") spec[keys] = v;
    else for (const id of keys) spec[id] = v;
  }
  return fill(spec, fallback);
}

export const SCENARIOS: Scenario[] = [
  {
    id: "rate_cut",
    name: "Interest Rate Cut (−0.5%)",
    short: "Rate cut",
    category: "macro",
    tone: "bull",
    blurb: "A 50bp easing cheapens duration and lifts risk appetite, led by long-duration tech, REITs, and high-beta crypto.",
    profile: "front",
    shocks: S([
      ["AAPL", 0.08], ["MSFT", 0.1], ["NVDA", 0.14], ["TSLA", 0.12], ["ASML", 0.11],
      ["RHM", 0.03], ["LLY", 0.07], ["MSTR", 0.22], ["CCJ", 0.06],
      ["SPX", 0.06], ["URTH", 0.05], ["QQQ", 0.09], ["TLT", 0.18], ["SMH", 0.12],
      ["ARKK", 0.2], ["BOTZ", 0.1], ["IGLN", -0.03], ["VNQ", 0.16],
      ["PIMIX", 0.05], ["FVST", 0.04],
      ["BTC", 0.18], ["ETH", 0.22], ["XRP", 0.15], ["SOL", 0.25],
      ["LINK", 0.16], ["RENDER", 0.2], ["TAO", 0.18], ["XMR", 0.1], ["UNI", 0.17], ["DOGE", 0.28],
    ]),
  },
  {
    id: "rate_hike",
    name: "Aggressive Rate Hike",
    short: "Rate hike",
    category: "macro",
    tone: "bear",
    blurb: "A hawkish surprise tightens financial conditions. Duration, REITs and speculative crypto de-lever first.",
    profile: "front",
    shocks: S([
      ["AAPL", -0.1], ["MSFT", -0.09], ["NVDA", -0.16], ["TSLA", -0.18], ["ASML", -0.14],
      ["RHM", 0.02], ["LLY", -0.06], ["MSTR", -0.28], ["CCJ", -0.08],
      ["SPX", -0.08], ["URTH", -0.07], ["QQQ", -0.12], ["TLT", -0.16], ["SMH", -0.15],
      ["ARKK", -0.24], ["BOTZ", -0.14], ["IGLN", 0.04], ["VNQ", -0.18],
      ["PIMIX", -0.06], ["FVST", -0.04],
      ["BTC", -0.22], ["ETH", -0.25], ["XRP", -0.28], ["SOL", -0.3],
      ["LINK", -0.24], ["RENDER", -0.3], ["TAO", -0.28], ["XMR", -0.18], ["UNI", -0.26], ["DOGE", -0.34],
    ]),
  },
  {
    id: "recession",
    name: "Global Recession",
    short: "Recession",
    category: "macro",
    tone: "bear",
    blurb: "A synchronized demand shock cuts earnings and risk premia. Cyclicals and high-beta names lead the drawdown.",
    profile: "delayed",
    shocks: S([
      ["AAPL", -0.18], ["MSFT", -0.14], ["NVDA", -0.28], ["TSLA", -0.32], ["ASML", -0.24],
      ["RHM", -0.08], ["LLY", -0.1], ["MSTR", -0.4], ["CCJ", -0.22],
      ["SPX", -0.22], ["URTH", -0.2], ["QQQ", -0.25], ["TLT", 0.1], ["SMH", -0.26],
      ["ARKK", -0.34], ["BOTZ", -0.22], ["IGLN", 0.08], ["VNQ", -0.2],
      ["PIMIX", -0.04], ["FVST", -0.06],
      ["BTC", -0.35], ["ETH", -0.4], ["XRP", -0.45], ["SOL", -0.42],
      ["LINK", -0.38], ["RENDER", -0.44], ["TAO", -0.4], ["XMR", -0.28], ["UNI", -0.4], ["DOGE", -0.5],
    ]),
  },
  {
    id: "ai_boom",
    name: "AI & Robotics Boom",
    short: "AI boom",
    category: "sector",
    tone: "bull",
    blurb: "A second-wave capex cycle in models, silicon, and physical automation. Pick-and-shovel names capture most of the re-rating.",
    profile: "gradual",
    shocks: S([
      ["AAPL", 0.12], ["MSFT", 0.18], ["NVDA", 0.45], ["TSLA", 0.22], ["ASML", 0.32],
      ["RHM", 0.02], ["LLY", 0.03], ["MSTR", 0.08], ["CCJ", 0.1],
      ["SPX", 0.08], ["URTH", 0.06], ["QQQ", 0.16], ["TLT", -0.03], ["SMH", 0.34],
      ["ARKK", 0.2], ["BOTZ", 0.38], ["IGLN", -0.02], ["VNQ", 0.02],
      ["PIMIX", 0.01], ["FVST", 0.05],
      ["BTC", 0.08], ["ETH", 0.1], ["XRP", 0.04], ["SOL", 0.15],
      ["LINK", 0.08], ["RENDER", 0.28], ["TAO", 0.32], ["XMR", 0.02], ["UNI", 0.06], ["DOGE", 0.05],
    ]),
  },
  {
    id: "taiwan",
    name: "Taiwan / Semiconductor Crisis",
    short: "Taiwan crisis",
    category: "geo",
    tone: "bear",
    blurb: "A blockade or kinetic shock to leading-edge fabs. ASML, NVIDIA and the hardware complex gap down; software is collateral.",
    profile: "immediate",
    shocks: S([
      ["AAPL", -0.08], ["MSFT", -0.06], ["NVDA", -0.38], ["TSLA", -0.1], ["ASML", -0.48],
      ["RHM", 0.14], ["LLY", -0.02], ["MSTR", -0.1], ["CCJ", 0.04],
      ["SPX", -0.07], ["URTH", -0.09], ["QQQ", -0.14], ["TLT", 0.04], ["SMH", -0.36],
      ["ARKK", -0.12], ["BOTZ", -0.16], ["IGLN", 0.08], ["VNQ", -0.03],
      ["PIMIX", 0.01], ["FVST", 0.02],
      ["BTC", -0.08], ["ETH", -0.1], ["XRP", -0.09], ["SOL", -0.11],
      ["LINK", -0.08], ["RENDER", -0.14], ["TAO", -0.1], ["XMR", -0.04], ["UNI", -0.08], ["DOGE", -0.1],
    ]),
  },
  {
    id: "crypto_ban",
    name: "Strict Global Crypto Ban",
    short: "Crypto ban",
    category: "geo",
    tone: "bear",
    blurb: "Coordinated prohibition of spot markets and on-ramps. Coins and MSTR gap; listed tech sees only a mild risk-off echo.",
    profile: "crash_recover",
    shocks: S([
      ["AAPL", -0.03], ["MSFT", -0.02], ["NVDA", -0.04], ["TSLA", -0.05], ["ASML", -0.03],
      ["RHM", 0], ["LLY", 0], ["MSTR", -0.62], ["CCJ", 0],
      ["SPX", -0.02], ["URTH", -0.02], ["QQQ", -0.03], ["TLT", 0.01], ["SMH", -0.03],
      ["ARKK", -0.06], ["BOTZ", -0.02], ["IGLN", 0.04], ["VNQ", 0],
      ["PIMIX", 0], ["FVST", 0.01],
      ["BTC", -0.55], ["ETH", -0.62], ["XRP", -0.7], ["SOL", -0.68],
      ["LINK", -0.6], ["RENDER", -0.64], ["TAO", -0.58], ["XMR", -0.42], ["UNI", -0.66], ["DOGE", -0.72],
    ]),
  },
  {
    id: "quantum",
    name: "Quantum Computing Breakthrough",
    short: "Quantum leap",
    category: "sector",
    tone: "mixed",
    blurb: "A credible fault-tolerant milestone re-rates cloud platforms and accelerators, and reprices cryptographic risk in coins.",
    profile: "delayed",
    shocks: S([
      ["AAPL", 0.06], ["MSFT", 0.2], ["NVDA", 0.15], ["TSLA", 0.08], ["ASML", 0.12],
      ["RHM", 0.04], ["LLY", 0.02], ["MSTR", -0.3], ["CCJ", 0.02],
      ["SPX", 0.05], ["URTH", 0.04], ["QQQ", 0.09], ["TLT", -0.01], ["SMH", 0.12],
      ["ARKK", 0.1], ["BOTZ", 0.08], ["IGLN", 0.02], ["VNQ", 0.01],
      ["PIMIX", 0], ["FVST", 0.03],
      ["BTC", -0.25], ["ETH", -0.3], ["XRP", -0.2], ["SOL", -0.22],
      ["LINK", -0.18], ["RENDER", -0.12], ["TAO", -0.08], ["XMR", -0.16], ["UNI", -0.2], ["DOGE", -0.14],
    ]),
  },
  {
    id: "hyperinflation",
    name: "Hyperinflation / Fiat Devaluation",
    short: "Fiat shock",
    category: "macro",
    tone: "mixed",
    blurb: "The unit of account fails. Nominal equities reprice; gold and hard-scarcity crypto are bid as monetary refuge.",
    profile: "accelerating",
    shocks: S([
      ["AAPL", 0.15], ["MSFT", 0.08], ["NVDA", 0.1], ["TSLA", 0.2], ["ASML", 0.08],
      ["RHM", 0.06], ["LLY", 0.05], ["MSTR", 0.7], ["CCJ", 0.18],
      ["SPX", 0.05], ["URTH", 0.04], ["QQQ", 0.07], ["TLT", -0.22], ["SMH", 0.08],
      ["ARKK", 0.1], ["BOTZ", 0.06], ["IGLN", 0.42], ["VNQ", 0.08],
      ["PIMIX", -0.1], ["FVST", 0.12],
      ["BTC", 0.65], ["ETH", 0.55], ["XRP", 0.4], ["SOL", 0.5],
      ["LINK", 0.38], ["RENDER", 0.32], ["TAO", 0.3], ["XMR", 0.48], ["UNI", 0.28], ["DOGE", 0.35],
    ]),
  },
  {
    id: "spot_etf",
    name: "Spot ETF Approvals Global",
    short: "Global crypto ETFs",
    category: "sector",
    tone: "bull",
    blurb: "Asian and European regulators open unrestricted crypto ETFs. Institutional pipes fill BTC, ETH and SOL; listed banks stagnate.",
    profile: "delayed",
    shocks: S([
      ["AAPL", 0.02], ["MSFT", 0.02], ["NVDA", 0.03], ["TSLA", 0.03], ["ASML", 0.02],
      ["RHM", 0], ["LLY", 0.01], ["MSTR", 0.48], ["CCJ", 0],
      ["SPX", 0.02], ["URTH", 0.02], ["QQQ", 0.03], ["TLT", -0.01], ["SMH", 0.02],
      ["ARKK", 0.06], ["BOTZ", 0.01], ["IGLN", -0.05], ["VNQ", 0.01],
      ["PIMIX", 0.01], ["FVST", 0.03],
      ["BTC", 0.38], ["ETH", 0.42], ["XRP", 0.22], ["SOL", 0.46],
      ["LINK", 0.28], ["RENDER", 0.16], ["TAO", 0.14], ["XMR", 0.06], ["UNI", 0.2], ["DOGE", 0.24],
    ]),
  },
  {
    id: "green_energy",
    name: "Green Energy Tech Breakthrough",
    short: "Fusion / battery leap",
    category: "sector",
    tone: "bull",
    blurb: "A step-change in generation or storage. Tesla and uranium re-rate; cheap energy is a slow bid under the broad book.",
    profile: "delayed",
    shocks: S([
      ["AAPL", 0.05], ["MSFT", 0.04], ["NVDA", 0.08], ["TSLA", 0.55], ["ASML", 0.06],
      ["RHM", -0.04], ["LLY", 0.02], ["MSTR", 0.04], ["CCJ", 0.42],
      ["SPX", 0.07], ["URTH", 0.08], ["QQQ", 0.06], ["TLT", 0.04], ["SMH", 0.05],
      ["ARKK", 0.16], ["BOTZ", 0.22], ["IGLN", -0.08], ["VNQ", 0.04],
      ["PIMIX", 0.02], ["FVST", 0.04],
      ["BTC", 0.04], ["ETH", 0.03], ["XRP", 0.02], ["SOL", 0.04],
      ["LINK", 0.03], ["RENDER", 0.05], ["TAO", 0.04], ["XMR", 0.01], ["UNI", 0.02], ["DOGE", 0.03],
    ]),
  },
  {
    id: "tax_cuts",
    name: "Global Tax Cuts & Deregulation",
    short: "Tax cuts",
    category: "macro",
    tone: "bull",
    blurb: "Corporate tax cuts and looser antitrust. Buybacks lift mega-cap tech; the S&P follows. Deficits nibble at long bonds.",
    profile: "front",
    shocks: S([
      ["AAPL", 0.18], ["MSFT", 0.16], ["NVDA", 0.14], ["TSLA", 0.12], ["ASML", 0.12],
      ["RHM", 0.06], ["LLY", 0.1], ["MSTR", 0.1], ["CCJ", 0.07],
      ["SPX", 0.14], ["URTH", 0.1], ["QQQ", 0.16], ["TLT", -0.05], ["SMH", 0.13],
      ["ARKK", 0.2], ["BOTZ", 0.1], ["IGLN", 0.02], ["VNQ", 0.08],
      ["PIMIX", 0.02], ["FVST", 0.06],
      ["BTC", 0.08], ["ETH", 0.09], ["XRP", 0.06], ["SOL", 0.1],
      ["LINK", 0.07], ["RENDER", 0.08], ["TAO", 0.07], ["XMR", 0.03], ["UNI", 0.08], ["DOGE", 0.12],
    ]),
  },
  {
    id: "web3",
    name: "Web3 / Metaverse Mainstream Adoption",
    short: "Web3 adoption",
    category: "sector",
    tone: "bull",
    blurb: "A consumer device with native crypto rails reaches daily use. Apple captures hardware; ETH, SOL and LINK take the rails.",
    profile: "gradual",
    shocks: S([
      ["AAPL", 0.24], ["MSFT", 0.08], ["NVDA", 0.12], ["TSLA", 0.06], ["ASML", 0.06],
      ["RHM", 0], ["LLY", 0], ["MSTR", 0.14], ["CCJ", 0],
      ["SPX", 0.04], ["URTH", 0.03], ["QQQ", 0.09], ["TLT", -0.02], ["SMH", 0.08],
      ["ARKK", 0.14], ["BOTZ", 0.06], ["IGLN", -0.02], ["VNQ", 0.01],
      ["PIMIX", 0], ["FVST", 0.03],
      ["BTC", 0.12], ["ETH", 0.38], ["XRP", 0.1], ["SOL", 0.42],
      ["LINK", 0.36], ["RENDER", 0.22], ["TAO", 0.12], ["XMR", 0.04], ["UNI", 0.32], ["DOGE", 0.18],
    ]),
  },
  {
    id: "peace",
    name: "Peace Treaty / End of Major Conflicts",
    short: "Peace treaty",
    category: "geo",
    tone: "bull",
    blurb: "A settlement of major conflicts. World equities and supply chains recover; defense and gold give back the fear premium.",
    profile: "delayed",
    shocks: S([
      ["AAPL", 0.08], ["MSFT", 0.05], ["NVDA", 0.06], ["TSLA", 0.07], ["ASML", 0.1],
      ["RHM", -0.3], ["LLY", 0.03], ["MSTR", -0.06], ["CCJ", -0.04],
      ["SPX", 0.1], ["URTH", 0.16], ["QQQ", 0.08], ["TLT", 0.03], ["SMH", 0.07],
      ["ARKK", 0.08], ["BOTZ", 0.05], ["IGLN", -0.12], ["VNQ", 0.08],
      ["PIMIX", 0.03], ["FVST", 0.04],
      ["BTC", -0.06], ["ETH", -0.04], ["XRP", -0.03], ["SOL", -0.04],
      ["LINK", -0.02], ["RENDER", -0.02], ["TAO", -0.02], ["XMR", -0.08], ["UNI", -0.02], ["DOGE", -0.03],
    ]),
  },
  {
    id: "qe_restart",
    name: "Central Bank QE Restart",
    short: "QE restart",
    category: "macro",
    tone: "bull",
    blurb: "The press runs again to fund sovereigns. Hard assets and duration catch the first bid; meme liquidity follows.",
    profile: "front",
    shocks: S([
      ["AAPL", 0.14], ["MSFT", 0.12], ["NVDA", 0.16], ["TSLA", 0.18], ["ASML", 0.1],
      ["RHM", 0.04], ["LLY", 0.06], ["MSTR", 0.5], ["CCJ", 0.08],
      ["SPX", 0.1], ["URTH", 0.08], ["QQQ", 0.13], ["TLT", 0.22], ["SMH", 0.12],
      ["ARKK", 0.28], ["BOTZ", 0.12], ["IGLN", 0.26], ["VNQ", 0.14],
      ["PIMIX", 0.06], ["FVST", 0.08],
      ["BTC", 0.4], ["ETH", 0.32], ["XRP", 0.24], ["SOL", 0.34],
      ["LINK", 0.22], ["RENDER", 0.26], ["TAO", 0.22], ["XMR", 0.16], ["UNI", 0.2], ["DOGE", 0.48],
    ]),
  },
  {
    id: "cyber_attack",
    name: "Global Cyber Attack on Financial Infrastructure",
    short: "Cyber attack",
    category: "geo",
    tone: "bear",
    blurb: "SWIFT, cards or exchanges go dark for days. Equities panic-sell; gold is bid. Coins gap, then try to reprice as an uncensored rail.",
    profile: "crash_recover",
    shocks: S([
      ["AAPL", -0.14], ["MSFT", -0.16], ["NVDA", -0.12], ["TSLA", -0.14], ["ASML", -0.1],
      ["RHM", 0.06], ["LLY", -0.08], ["MSTR", -0.18], ["CCJ", -0.06],
      ["SPX", -0.18], ["URTH", -0.14], ["QQQ", -0.16], ["TLT", 0.08], ["SMH", -0.12],
      ["ARKK", -0.16], ["BOTZ", -0.1], ["IGLN", 0.24], ["VNQ", -0.1],
      ["PIMIX", -0.05], ["FVST", 0.02],
      ["BTC", -0.12], ["ETH", -0.18], ["XRP", -0.22], ["SOL", -0.2],
      ["LINK", -0.16], ["RENDER", -0.18], ["TAO", -0.14], ["XMR", 0.12], ["UNI", -0.24], ["DOGE", -0.2],
    ]),
  },
  {
    id: "cre_crash",
    name: "Commercial Real Estate Crash",
    short: "CRE crash",
    category: "macro",
    tone: "bear",
    blurb: "Office values gap as regional banks crack. REITs lead the drawdown; fortress tech holds. DeFi and BTC catch a distrust bid.",
    profile: "delayed",
    shocks: S([
      ["AAPL", -0.04], ["MSFT", -0.03], ["NVDA", -0.05], ["TSLA", -0.06], ["ASML", -0.04],
      ["RHM", -0.02], ["LLY", -0.03], ["MSTR", 0.1], ["CCJ", -0.03],
      ["SPX", -0.12], ["URTH", -0.08], ["QQQ", -0.06], ["TLT", 0.06], ["SMH", -0.05],
      ["ARKK", -0.08], ["BOTZ", -0.04], ["IGLN", 0.06], ["VNQ", -0.4],
      ["PIMIX", -0.12], ["FVST", -0.07],
      ["BTC", 0.12], ["ETH", 0.1], ["XRP", 0.04], ["SOL", 0.08],
      ["LINK", 0.1], ["RENDER", 0.04], ["TAO", 0.03], ["XMR", 0.08], ["UNI", 0.2], ["DOGE", 0.06],
    ]),
  },
  {
    id: "ai_reg",
    name: "AI Regulation & Copyright Crackdown",
    short: "AI clampdown",
    category: "sector",
    tone: "bear",
    blurb: "Unlicensed training is barred and fines land on the labs. Microsoft, NVIDIA and the Nasdaq re-rate down; decentralized AI catches the overflow.",
    profile: "front",
    shocks: S([
      ["AAPL", -0.08], ["MSFT", -0.28], ["NVDA", -0.32], ["TSLA", -0.1], ["ASML", -0.14],
      ["RHM", 0], ["LLY", 0.01], ["MSTR", 0.02], ["CCJ", 0],
      ["SPX", -0.08], ["URTH", -0.06], ["QQQ", -0.18], ["TLT", 0.03], ["SMH", -0.22],
      ["ARKK", -0.2], ["BOTZ", -0.16], ["IGLN", 0.02], ["VNQ", 0],
      ["PIMIX", 0.01], ["FVST", -0.02],
      ["BTC", 0.04], ["ETH", 0.06], ["XRP", 0.02], ["SOL", 0.05],
      ["LINK", 0.04], ["RENDER", 0.32], ["TAO", 0.38], ["XMR", 0.03], ["UNI", 0.04], ["DOGE", 0.02],
    ]),
  },
  {
    id: "solar_flare",
    name: "Solar Flare / Global Grid Failure",
    short: "Grid failure",
    category: "geo",
    tone: "bear",
    blurb: "A Carrington-class event darkens grids and the net. Anything that lives on electricity is marked down; gold keeps a bid.",
    profile: "immediate",
    shocks: S([
      ["AAPL", -0.22], ["MSFT", -0.2], ["NVDA", -0.3], ["TSLA", -0.26], ["ASML", -0.18],
      ["RHM", 0.04], ["LLY", -0.12], ["MSTR", -0.5], ["CCJ", -0.08],
      ["SPX", -0.2], ["URTH", -0.18], ["QQQ", -0.24], ["TLT", 0.05], ["SMH", -0.26],
      ["ARKK", -0.28], ["BOTZ", -0.22], ["IGLN", 0.2], ["VNQ", -0.1],
      ["PIMIX", -0.03], ["FVST", 0.04],
      ["BTC", -0.58], ["ETH", -0.62], ["XRP", -0.6], ["SOL", -0.64],
      ["LINK", -0.6], ["RENDER", -0.66], ["TAO", -0.62], ["XMR", -0.52], ["UNI", -0.64], ["DOGE", -0.7],
    ]),
  },
  {
    id: "dedollar",
    name: "De-Dollarization Acceleration",
    short: "De-dollarization",
    category: "macro",
    tone: "bear",
    blurb: "A gold-linked BRICS unit and Treasury dumping hit the US book. Gold and BTC reprice as neutral money; TLT and the S&P give way.",
    profile: "accelerating",
    shocks: S([
      ["AAPL", -0.1], ["MSFT", -0.12], ["NVDA", -0.1], ["TSLA", -0.08], ["ASML", -0.04],
      ["RHM", 0.08], ["LLY", -0.06], ["MSTR", 0.28], ["CCJ", 0.1],
      ["SPX", -0.2], ["URTH", 0.06], ["QQQ", -0.16], ["TLT", -0.24], ["SMH", -0.1],
      ["ARKK", -0.12], ["BOTZ", -0.06], ["IGLN", 0.4], ["VNQ", -0.1],
      ["PIMIX", -0.14], ["FVST", 0.08],
      ["BTC", 0.32], ["ETH", 0.18], ["XRP", 0.12], ["SOL", 0.16],
      ["LINK", 0.14], ["RENDER", 0.08], ["TAO", 0.08], ["XMR", 0.2], ["UNI", 0.1], ["DOGE", 0.08],
    ]),
  },
  {
    id: "tether",
    name: "Tether (USDT) Collapse",
    short: "Tether collapse",
    category: "sector",
    tone: "bear",
    blurb: "The largest dollar stablecoin is shown to be under-reserved. Crypto liquidity vanishes; listed equities print a near-zero beta.",
    profile: "crash_recover",
    shocks: S([
      ["AAPL", 0], ["MSFT", 0], ["NVDA", -0.01], ["TSLA", 0], ["ASML", 0],
      ["RHM", 0], ["LLY", 0], ["MSTR", -0.58], ["CCJ", 0],
      ["SPX", 0], ["URTH", 0], ["QQQ", -0.01], ["TLT", 0.01], ["SMH", 0],
      ["ARKK", -0.02], ["BOTZ", 0], ["IGLN", 0.03], ["VNQ", 0],
      ["PIMIX", 0], ["FVST", 0],
      ["BTC", -0.62], ["ETH", -0.7], ["XRP", -0.76], ["SOL", -0.72],
      ["LINK", -0.66], ["RENDER", -0.7], ["TAO", -0.6], ["XMR", -0.42], ["UNI", -0.74], ["DOGE", -0.8],
    ]),
  },
];

export const SCENARIO_BY_ID: Record<ScenarioId, Scenario> = Object.fromEntries(
  SCENARIOS.map((s) => [s.id, s]),
) as Record<ScenarioId, Scenario>;

export const SCENARIO_IDS = SCENARIOS.map((s) => s.id);

export const INTERACTIONS: Interaction[] = [
  {
    id: "cheap-ai",
    kind: "compound",
    pair: ["rate_cut", "ai_boom"],
    label: "Cheap money fuels the AI capex cycle",
    detail: "Lower discount rates duration-extend model and silicon spend. Tech, SMH and QQQ get an extra bid beyond the sum of parts.",
  },
  {
    id: "volcker-recession",
    kind: "compound",
    pair: ["rate_hike", "recession"],
    label: "Tight policy into contracting demand",
    detail: "A hike into a recession compounds the earnings and multiple hit. High-beta names and ARKK gap further.",
  },
  {
    id: "liq-vs-cashflow",
    kind: "conflict",
    pair: ["rate_cut", "recession"],
    label: "Liquidity eases as cash-flows shrink",
    detail: "The cut supports valuations while the recession cuts earnings. Net path is muted and the cone widens.",
  },
  {
    id: "ease-into-fiat",
    kind: "conflict",
    pair: ["rate_cut", "hyperinflation"],
    label: "Easing into a fiat shock",
    detail: "Nominal risk assets get mixed signals. Gold and crypto inherit more of the devaluation bid; the cut’s equity boost halves.",
  },
  {
    id: "stagflation",
    kind: "compound",
    pair: ["rate_hike", "hyperinflation"],
    label: "Stagflationary squeeze",
    detail: "A Volcker-style hike into sticky prices crushes duration. BTC and gold still hedge the unit-of-account failure, but less cleanly.",
  },
  {
    id: "wafers-vs-models",
    kind: "conflict",
    pair: ["taiwan", "ai_boom"],
    label: "Model demand without wafers",
    detail: "AI spend wants more silicon than a Taiwan shock can ship. NVIDIA and ASML are capped; software holds up better than hardware.",
  },
  {
    id: "supply-into-hole",
    kind: "compound",
    pair: ["taiwan", "recession"],
    label: "Supply shock into a demand hole",
    detail: "A fab crisis in a recession is doubly deflationary for hardware and risk-off for everything else.",
  },
  {
    id: "outlawed-hedge",
    kind: "conflict",
    pair: ["crypto_ban", "hyperinflation"],
    label: "The hedge is outlawed as the unit fails",
    detail: "Fiat devaluation wants a crypto bid the ban forbids. Coins settle in a wide, residual underground range. Gold takes the flow.",
  },
  {
    id: "liq-out-legal-out",
    kind: "compound",
    pair: ["crypto_ban", "rate_hike"],
    label: "Liquidity out, legal out",
    detail: "A hike and a ban drain both the speculative bid and the on-ramp. Crypto and MSTR drawdowns stack.",
  },
  {
    id: "protocol-plus-ban",
    kind: "compound",
    pair: ["quantum", "crypto_ban"],
    label: "Protocol risk plus prohibition",
    detail: "A cryptographic scare and a legal ban are the same trade for coins — both empty the bid.",
  },
  {
    id: "second-s-curve",
    kind: "compound",
    pair: ["quantum", "ai_boom"],
    label: "A second compute S-curve",
    detail: "Quantum and AI spend land on the same pick-and-shovel complex. Microsoft, NVIDIA and SMH compound.",
  },
  {
    id: "algos-need-fabs",
    kind: "conflict",
    pair: ["taiwan", "quantum"],
    label: "Breakthroughs still need leading-edge fabs",
    detail: "A quantum milestone does not ship without TSMC-class process. ASML and NVIDIA upside is bound by the island.",
  },
  {
    id: "etf-plus-qe",
    kind: "compound",
    pair: ["spot_etf", "qe_restart"],
    label: "Pipes open into a liquidity wave",
    detail: "New ETF on-ramps meet QE. BTC, ETH, SOL and MSTR take a larger bid than either event alone.",
  },
  {
    id: "etf-vs-ban",
    kind: "conflict",
    pair: ["spot_etf", "crypto_ban"],
    label: "A product without a legal market",
    detail: "Approvals are worthless if the underlying is prohibited. The ETF bid and the ban cancel; the cone is the story.",
  },
  {
    id: "etf-vs-tether",
    kind: "conflict",
    pair: ["spot_etf", "tether"],
    label: "Institutional pipes into a liquidity vacuum",
    detail: "ETF demand wants coins the Tether collapse cannot price. Majors gap; listed names stay almost still.",
  },
  {
    id: "tax-plus-cut",
    kind: "compound",
    pair: ["tax_cuts", "rate_cut"],
    label: "Fiscal and monetary easing together",
    detail: "Buybacks and a lower discount rate are the same trade for mega-cap tech. The S&P and QQQ compound.",
  },
  {
    id: "qe-vs-hike",
    kind: "conflict",
    pair: ["qe_restart", "rate_hike"],
    label: "The press versus the hike",
    detail: "One desk is injecting duration, the other is draining it. Gold and BTC keep more of the bid than TLT.",
  },
  {
    id: "qe-plus-fiat",
    kind: "compound",
    pair: ["qe_restart", "hyperinflation"],
    label: "Monetisation as the unit fails",
    detail: "QE into a fiat shock is the gold-and-bitcoin tape. Duration is offered; IGLN and BTC take the flow.",
  },
  {
    id: "web3-plus-etf",
    kind: "compound",
    pair: ["web3", "spot_etf"],
    label: "Consumer rails plus institutional pipes",
    detail: "A daily-use device and a global ETF complex feed the same coins. ETH, SOL and LINK pull away from BTC.",
  },
  {
    id: "web3-vs-ban",
    kind: "conflict",
    pair: ["web3", "crypto_ban"],
    label: "A native-crypto device in a banned market",
    detail: "Hardware can ship; the rails cannot. Apple keeps some of the device bid; coins are capped.",
  },
  {
    id: "ai-vs-clamp",
    kind: "conflict",
    pair: ["ai_boom", "ai_reg"],
    label: "Capex cycle under a copyright bar",
    detail: "The boom wants more models than a clampdown will license. NVIDIA and MSFT are capped; TAO and RENDER inherit the overflow.",
  },
  {
    id: "taiwan-plus-clamp",
    kind: "compound",
    pair: ["taiwan", "ai_reg"],
    label: "No wafers, no license",
    detail: "A fab shock and an AI fine are the same trade for NVIDIA and SMH — both empty the multiple.",
  },
  {
    id: "cre-plus-hike",
    kind: "compound",
    pair: ["cre_crash", "rate_hike"],
    label: "Offices into tighter money",
    detail: "A hike into a CRE gap is how regional-bank stress becomes a REIT event. VNQ and PIMIX stack the loss.",
  },
  {
    id: "cre-vs-cut",
    kind: "conflict",
    pair: ["cre_crash", "rate_cut"],
    label: "A cut that arrives after the vacancy",
    detail: "Cheaper money supports cap rates the occupancy shock is still cutting. VNQ’s path is wide, not clean.",
  },
  {
    id: "peace-vs-taiwan",
    kind: "conflict",
    pair: ["peace", "taiwan"],
    label: "A settlement that is not this island",
    detail: "Broader peace does not restock TSMC. World equities recover; ASML and NVIDIA stay bound to the strait.",
  },
  {
    id: "flare-plus-tether",
    kind: "compound",
    pair: ["solar_flare", "tether"],
    label: "The rail and the dollar-peg both fail",
    detail: "A dark grid and a broken stablecoin are the same trade for coins. Gold is the residual store.",
  },
  {
    id: "dedollar-plus-fiat",
    kind: "compound",
    pair: ["dedollar", "hyperinflation"],
    label: "The reserve currency and the unit fail together",
    detail: "Treasury dumping into a fiat shock is the IGLN tape. BTC tags along as neutral money; TLT is offered.",
  },
  {
    id: "green-vs-flare",
    kind: "conflict",
    pair: ["green_energy", "solar_flare"],
    label: "A breakthrough that cannot be plugged in",
    detail: "Cheap energy is a 2028 story; a dark grid is a this-week story. Tesla’s leap is postponed, not cancelled.",
  },
  {
    id: "ban-plus-tether",
    kind: "compound",
    pair: ["crypto_ban", "tether"],
    label: "Legal out, dollar-peg out",
    detail: "A ban and a USDT gap empty both the on-ramp and the quote. Coins print the floor; equities barely move.",
  },
];

export type Preset = {
  id: string;
  name: string;
  desc: string;
  set: Partial<Record<ScenarioId, number>>;
};

export const PRESETS: Preset[] = [
  { id: "soft_landing", name: "Soft landing", desc: "A clean 50bp cut", set: { rate_cut: 80 } },
  { id: "ai_supercycle", name: "AI supercycle", desc: "Cheap money plus robotics", set: { rate_cut: 70, ai_boom: 100 } },
  { id: "stagflation", name: "Stagflation", desc: "Hike into a fiat shock", set: { rate_hike: 80, hyperinflation: 70 } },
  { id: "chip_shock", name: "Chip shock", desc: "Taiwan into AI demand", set: { taiwan: 100, ai_boom: 80 } },
  { id: "crypto_winter", name: "Crypto winter", desc: "Ban plus a hike", set: { crypto_ban: 100, rate_hike: 70 } },
  { id: "fiat_break", name: "Fiat break", desc: "Devaluation with residual easing", set: { hyperinflation: 90, rate_cut: 60 } },
  { id: "hard_landing", name: "Hard landing", desc: "Recession plus a hike", set: { recession: 90, rate_hike: 70 } },
  { id: "quantum_era", name: "Quantum era", desc: "Compute on an AI base", set: { quantum: 85, ai_boom: 70 } },
  { id: "etf_wave", name: "ETF wave", desc: "Global crypto ETFs", set: { spot_etf: 100 } },
  { id: "fusion_age", name: "Fusion age", desc: "Energy breakthrough", set: { green_energy: 100 } },
  { id: "liquidity", name: "Liquidity", desc: "QE plus tax cuts", set: { qe_restart: 90, tax_cuts: 70 } },
  { id: "web3_wave", name: "Web3 wave", desc: "Adoption plus ETFs", set: { web3: 90, spot_etf: 60 } },
  { id: "ai_clamp", name: "AI clamp", desc: "Boom under a copyright bar", set: { ai_boom: 70, ai_reg: 100 } },
  { id: "office_bust", name: "Office bust", desc: "CRE plus a hike", set: { cre_crash: 90, rate_hike: 70 } },
  { id: "dollar_break", name: "Dollar break", desc: "De-dollar plus fiat", set: { dedollar: 90, hyperinflation: 60 } },
  { id: "usdt_gap", name: "USDT gap", desc: "Tether collapse", set: { tether: 100 } },
  { id: "blackout", name: "Blackout", desc: "Grid failure", set: { solar_flare: 100 } },
  { id: "pax", name: "Pax", desc: "Peace treaty", set: { peace: 100 } },
];

export const DEFAULT_WEIGHTS: Record<ScenarioId, number> = Object.fromEntries(
  SCENARIO_IDS.map((id) => [id, 100]),
) as Record<ScenarioId, number>;

export const DEFAULT_VISIBLE: AssetId[] = ["AAPL", "MSFT", "NVDA", "TSLA", "BTC"];

export const CLASS_LABEL: Record<Asset["class"], string> = {
  equity: "Equity",
  etf: "ETF",
  fund: "Fund",
  crypto: "Crypto",
};
