import type {
  Asset,
  AssetId,
  Interaction,
  Scenario,
  ScenarioId,
  ShockMap,
} from "./types";

export const AS_OF = "2026-08-18";
export const AS_OF_LABEL = "18 Aug 2026";

export const ASSETS: Asset[] = [
  { id: "AAPL", ticker: "AAPL", name: "Apple", class: "equity", last: 306.7, kind: "usd", mu: 0.11, sigma: 0.24, colorVar: "var(--color-aapl)" },
  { id: "MSFT", ticker: "MSFT", name: "Microsoft", class: "equity", last: 478.16, kind: "usd", mu: 0.13, sigma: 0.23, colorVar: "var(--color-msft)" },
  { id: "NVDA", ticker: "NVDA", name: "NVIDIA", class: "equity", last: 220.07, kind: "usd", mu: 0.22, sigma: 0.42, colorVar: "var(--color-nvda)" },
  { id: "TSLA", ticker: "TSLA", name: "Tesla", class: "equity", last: 332.59, kind: "usd", mu: 0.14, sigma: 0.52, colorVar: "var(--color-tsla)" },
  { id: "ASML", ticker: "ASML", name: "ASML", class: "equity", last: 1788, kind: "usd", mu: 0.16, sigma: 0.38, colorVar: "var(--color-asml)" },
  { id: "RHM", ticker: "RHM", name: "Rheinmetall", class: "equity", last: 1214, kind: "usd", mu: 0.1, sigma: 0.44, colorVar: "var(--color-rhm)" },
  { id: "LLY", ticker: "LLY", name: "Eli Lilly", class: "equity", last: 1215, kind: "usd", mu: 0.12, sigma: 0.32, colorVar: "var(--color-lly)" },
  { id: "MSTR", ticker: "MSTR", name: "Strategy", class: "equity", last: 94, kind: "usd", mu: 0.2, sigma: 0.82, colorVar: "var(--color-mstr)" },
  { id: "CCJ", ticker: "CCJ", name: "Cameco", class: "equity", last: 95.5, kind: "usd", mu: 0.13, sigma: 0.48, colorVar: "var(--color-ccj)" },
  { id: "AMZN", ticker: "AMZN", name: "Amazon", class: "equity", last: 261.31, kind: "usd", mu: 0.13, sigma: 0.28, colorVar: "var(--color-amzn)" },
  { id: "CRWD", ticker: "CRWD", name: "CrowdStrike", class: "equity", last: 212.96, kind: "usd", mu: 0.16, sigma: 0.46, colorVar: "var(--color-crwd)" },
  { id: "WMT", ticker: "WMT", name: "Walmart", class: "equity", last: 115.58, kind: "usd", mu: 0.08, sigma: 0.18, colorVar: "var(--color-wmt)" },
  { id: "NVO", ticker: "NVO", name: "Novo Nordisk", class: "equity", last: 98.4, kind: "usd", mu: 0.11, sigma: 0.34, colorVar: "var(--color-nvo)" },
  { id: "LMT", ticker: "LMT", name: "Lockheed Martin", class: "equity", last: 478, kind: "usd", mu: 0.08, sigma: 0.22, colorVar: "var(--color-lmt)" },
  { id: "SPX", ticker: "SPX", name: "S&P 500", class: "etf", last: 7730, kind: "index", mu: 0.08, sigma: 0.16, colorVar: "var(--color-spx)" },
  { id: "URTH", ticker: "URTH", name: "MSCI World", class: "etf", last: 208.4, kind: "usd", mu: 0.07, sigma: 0.15, colorVar: "var(--color-urth)" },
  { id: "QQQ", ticker: "QQQ", name: "Nasdaq 100", class: "etf", last: 628.2, kind: "usd", mu: 0.12, sigma: 0.22, colorVar: "var(--color-qqq)" },
  { id: "TLT", ticker: "TLT", name: "20Y Treasury", class: "etf", last: 88.6, kind: "usd", mu: 0.02, sigma: 0.14, colorVar: "var(--color-tlt)" },
  { id: "SMH", ticker: "SMH", name: "VanEck Semi", class: "etf", last: 312, kind: "usd", mu: 0.16, sigma: 0.34, colorVar: "var(--color-smh)" },
  { id: "ARKK", ticker: "ARKK", name: "ARK Innovation", class: "etf", last: 54.2, kind: "usd", mu: 0.08, sigma: 0.48, colorVar: "var(--color-arkk)" },
  { id: "BOTZ", ticker: "BOTZ", name: "Robotics & AI", class: "etf", last: 35.4, kind: "usd", mu: 0.11, sigma: 0.3, colorVar: "var(--color-botz)" },
  { id: "IGLN", ticker: "IGLN", name: "Physical Gold", class: "etf", last: 85.18, kind: "usd", mu: 0.04, sigma: 0.16, colorVar: "var(--color-igln)" },
  { id: "VNQ", ticker: "VNQ", name: "US Real Estate", class: "etf", last: 97.98, kind: "usd", mu: 0.06, sigma: 0.2, colorVar: "var(--color-vnq)" },
  { id: "DBA", ticker: "DBA", name: "Ag Commodities", class: "etf", last: 27.78, kind: "usd", mu: 0.03, sigma: 0.2, colorVar: "var(--color-dba)" },
  { id: "PIMIX", ticker: "PIMIX", name: "PIMCO Income", class: "fund", last: 10.73, kind: "usd", mu: 0.045, sigma: 0.06, colorVar: "var(--color-pimix)" },
  { id: "FVST", ticker: "FVST", name: "FvS Multi Opp", class: "fund", last: 199.4, kind: "usd", mu: 0.06, sigma: 0.1, colorVar: "var(--color-fvst)" },
  { id: "BTC", ticker: "BTC", name: "Bitcoin", class: "crypto", last: 64755, kind: "crypto", mu: 0.18, sigma: 0.58, colorVar: "var(--color-btc)" },
  { id: "ETH", ticker: "ETH", name: "Ethereum", class: "crypto", last: 1916, kind: "crypto", mu: 0.16, sigma: 0.66, colorVar: "var(--color-eth)" },
  { id: "XRP", ticker: "XRP", name: "Ripple", class: "crypto", last: 1.001, kind: "crypto", mu: 0.1, sigma: 0.72, colorVar: "var(--color-xrp)" },
  { id: "SOL", ticker: "SOL", name: "Solana", class: "crypto", last: 76.95, kind: "crypto", mu: 0.2, sigma: 0.78, colorVar: "var(--color-sol)" },
  { id: "LINK", ticker: "LINK", name: "Chainlink", class: "crypto", last: 9.48, kind: "crypto", mu: 0.14, sigma: 0.74, colorVar: "var(--color-link)" },
  { id: "RENDER", ticker: "RENDER", name: "Render", class: "crypto", last: 1.27, kind: "crypto", mu: 0.18, sigma: 0.88, colorVar: "var(--color-render)" },
  { id: "TAO", ticker: "TAO", name: "Bittensor", class: "crypto", last: 192, kind: "crypto", mu: 0.22, sigma: 0.92, colorVar: "var(--color-tao)" },
  { id: "XMR", ticker: "XMR", name: "Monero", class: "crypto", last: 415, kind: "crypto", mu: 0.08, sigma: 0.7, colorVar: "var(--color-xmr)" },
  { id: "UNI", ticker: "UNI", name: "Uniswap", class: "crypto", last: 3.28, kind: "crypto", mu: 0.12, sigma: 0.8, colorVar: "var(--color-uni)" },
  { id: "DOGE", ticker: "DOGE", name: "Dogecoin", class: "crypto", last: 0.0701, kind: "crypto", mu: 0.05, sigma: 0.95, colorVar: "var(--color-doge)" },
];

export const ASSET_BY_ID: Record<AssetId, Asset> = Object.fromEntries(
  ASSETS.map((a) => [a.id, a]),
) as Record<AssetId, Asset>;

export const ASSET_IDS = ASSETS.map((a) => a.id);

export const TECH: AssetId[] = ["AAPL", "MSFT", "NVDA", "TSLA", "ASML", "AMZN", "CRWD", "QQQ", "SMH", "ARKK", "BOTZ"];
export const CRYPTO: AssetId[] = ["BTC", "ETH", "XRP", "SOL", "LINK", "RENDER", "TAO", "XMR", "UNI", "DOGE"];
export const HARDWARE: AssetId[] = ["NVDA", "ASML", "SMH", "AAPL", "TSLA"];
export const SEMI: AssetId[] = ["NVDA", "ASML", "SMH"];
export const GOLD: AssetId[] = ["IGLN"];
export const DURATION: AssetId[] = ["TLT", "PIMIX"];
export const AI_DECENTRAL: AssetId[] = ["TAO", "RENDER"];

function fill(spec: Partial<ShockMap>, fallback = 0): ShockMap {
  const out = {} as ShockMap;
  for (const id of ASSET_IDS) out[id] = spec[id] ?? fallback;
  return out;
}

function S(rows: Array<[AssetId | readonly AssetId[], number]>, fallback = 0): ShockMap {
  const spec: Partial<ShockMap> = {};
  for (const [keys, v] of rows) {
    if (typeof keys === "string") spec[keys] = v;
    else for (const id of keys) spec[id] = v;
  }
  return fill(spec, fallback);
}

export const SCENARIOS: Scenario[] = [
  {
    id: "rate_cut",
    name: "Interest Rate Cut (−0.5%)",
    short: "Rate cut",
    category: "macro",
    tone: "bull",
    blurb: "A 50bp easing cheapens duration and lifts risk appetite, led by long-duration tech, REITs, and high-beta crypto.",
    profile: "front",
    shocks: S([
      ["AAPL", 0.08], ["MSFT", 0.1], ["NVDA", 0.14], ["TSLA", 0.12], ["ASML", 0.11],
      ["RHM", 0.03], ["LLY", 0.07], ["MSTR", 0.22], ["CCJ", 0.06],
      ["SPX", 0.06], ["URTH", 0.05], ["QQQ", 0.09], ["TLT", 0.18], ["SMH", 0.12],
      ["ARKK", 0.2], ["BOTZ", 0.1], ["IGLN", -0.03], ["VNQ", 0.16],
      ["PIMIX", 0.05], ["FVST", 0.04],
      ["BTC", 0.18], ["ETH", 0.22], ["XRP", 0.15], ["SOL", 0.25],
      ["LINK", 0.16], ["RENDER", 0.2], ["TAO", 0.18], ["XMR", 0.1], ["UNI", 0.17], ["DOGE", 0.28],
    ]),
  },
  {
    id: "rate_hike",
    name: "Aggressive Rate Hike",
    short: "Rate hike",
    category: "macro",
    tone: "bear",
    blurb: "A hawkish surprise tightens financial conditions. Duration, REITs and speculative crypto de-lever first.",
    profile: "front",
    shocks: S([
      ["AAPL", -0.1], ["MSFT", -0.09], ["NVDA", -0.16], ["TSLA", -0.18], ["ASML", -0.14],
      ["RHM", 0.02], ["LLY", -0.06], ["MSTR", -0.28], ["CCJ", -0.08],
      ["SPX", -0.08], ["URTH", -0.07], ["QQQ", -0.12], ["TLT", -0.16], ["SMH", -0.15],
      ["ARKK", -0.24], ["BOTZ", -0.14], ["IGLN", 0.04], ["VNQ", -0.18],
      ["PIMIX", -0.06], ["FVST", -0.04],
      ["BTC", -0.22], ["ETH", -0.25], ["XRP", -0.28], ["SOL", -0.3],
      ["LINK", -0.24], ["RENDER", -0.3], ["TAO", -0.28], ["XMR", -0.18], ["UNI", -0.26], ["DOGE", -0.34],
    ]),
  },
  {
    id: "recession",
    name: "Global Recession",
    short: "Recession",
    category: "macro",
    tone: "bear",
    blurb: "A synchronized demand shock cuts earnings and risk premia. Cyclicals and high-beta names lead the drawdown.",
    profile: "delayed",
    shocks: S([
      ["AAPL", -0.18], ["MSFT", -0.14], ["NVDA", -0.28], ["TSLA", -0.32], ["ASML", -0.24],
      ["RHM", -0.08], ["LLY", -0.1], ["MSTR", -0.4], ["CCJ", -0.22],
      ["SPX", -0.22], ["URTH", -0.2], ["QQQ", -0.25], ["TLT", 0.1], ["SMH", -0.26],
      ["ARKK", -0.34], ["BOTZ", -0.22], ["IGLN", 0.08], ["VNQ", -0.2],
      ["PIMIX", -0.04], ["FVST", -0.06],
      ["BTC", -0.35], ["ETH", -0.4], ["XRP", -0.45], ["SOL", -0.42],
      ["LINK", -0.38], ["RENDER", -0.44], ["TAO", -0.4], ["XMR", -0.28], ["UNI", -0.4], ["DOGE", -0.5],
    ]),
  },
  {
    id: "ai_boom",
    name: "AI & Robotics Boom",
    short: "AI boom",
    category: "sector",
    tone: "bull",
    blurb: "A second-wave capex cycle in models, silicon, and physical automation. Pick-and-shovel names capture most of the re-rating.",
    profile: "gradual",
    shocks: S([
      ["AAPL", 0.12], ["MSFT", 0.18], ["NVDA", 0.45], ["TSLA", 0.22], ["ASML", 0.32],
      ["RHM", 0.02], ["LLY", 0.03], ["MSTR", 0.08], ["CCJ", 0.1],
      ["SPX", 0.08], ["URTH", 0.06], ["QQQ", 0.16], ["TLT", -0.03], ["SMH", 0.34],
      ["ARKK", 0.2], ["BOTZ", 0.38], ["IGLN", -0.02], ["VNQ", 0.02],
      ["PIMIX", 0.01], ["FVST", 0.05],
      ["BTC", 0.08], ["ETH", 0.1], ["XRP", 0.04], ["SOL", 0.15],
      ["LINK", 0.08], ["RENDER", 0.28], ["TAO", 0.32], ["XMR", 0.02], ["UNI", 0.06], ["DOGE", 0.05],
    ]),
  },
  {
    id: "taiwan",
    name: "Taiwan / Semiconductor Crisis",
    short: "Taiwan crisis",
    category: "geo",
    tone: "bear",
    blurb: "A blockade or kinetic shock to leading-edge fabs. ASML, NVIDIA and the hardware complex gap down; software is collateral.",
    profile: "immediate",
    shocks: S([
      ["AAPL", -0.08], ["MSFT", -0.06], ["NVDA", -0.38], ["TSLA", -0.1], ["ASML", -0.48],
      ["RHM", 0.14], ["LLY", -0.02], ["MSTR", -0.1], ["CCJ", 0.04],
      ["SPX", -0.07], ["URTH", -0.09], ["QQQ", -0.14], ["TLT", 0.04], ["SMH", -0.36],
      ["ARKK", -0.12], ["BOTZ", -0.16], ["IGLN", 0.08], ["VNQ", -0.03],
      ["PIMIX", 0.01], ["FVST", 0.02],
      ["BTC", -0.08], ["ETH", -0.1], ["XRP", -0.09], ["SOL", -0.11],
      ["LINK", -0.08], ["RENDER", -0.14], ["TAO", -0.1], ["XMR", -0.04], ["UNI", -0.08], ["DOGE", -0.1],
    ]),
  },
  {
    id: "crypto_ban",
    name: "Strict Global Crypto Ban",
    short: "Crypto ban",
    category: "geo",
    tone: "bear",
    blurb: "Coordinated prohibition of spot markets and on-ramps. Coins and MSTR gap; listed tech sees only a mild risk-off echo.",
    profile: "crash_recover",
    shocks: S([
      ["AAPL", -0.03], ["MSFT", -0.02], ["NVDA", -0.04], ["TSLA", -0.05], ["ASML", -0.03],
      ["RHM", 0], ["LLY", 0], ["MSTR", -0.62], ["CCJ", 0],
      ["SPX", -0.02], ["URTH", -0.02], ["QQQ", -0.03], ["TLT", 0.01], ["SMH", -0.03],
      ["ARKK", -0.06], ["BOTZ", -0.02], ["IGLN", 0.04], ["VNQ", 0],
      ["PIMIX", 0], ["FVST", 0.01],
      ["BTC", -0.55], ["ETH", -0.62], ["XRP", -0.7], ["SOL", -0.68],
      ["LINK", -0.6], ["RENDER", -0.64], ["TAO", -0.58], ["XMR", -0.42], ["UNI", -0.66], ["DOGE", -0.72],
    ]),
  },
  {
    id: "quantum",
    name: "Quantum Computing Breakthrough",
    short: "Quantum leap",
    category: "sector",
    tone: "mixed",
    blurb: "A credible fault-tolerant milestone re-rates cloud platforms and accelerators, and reprices cryptographic risk in coins.",
    profile: "delayed",
    shocks: S([
      ["AAPL", 0.06], ["MSFT", 0.2], ["NVDA", 0.15], ["TSLA", 0.08], ["ASML", 0.12],
      ["RHM", 0.04], ["LLY", 0.02], ["MSTR", -0.3], ["CCJ", 0.02],
      ["SPX", 0.05], ["URTH", 0.04], ["QQQ", 0.09], ["TLT", -0.01], ["SMH", 0.12],
      ["ARKK", 0.1], ["BOTZ", 0.08], ["IGLN", 0.02], ["VNQ", 0.01],
      ["PIMIX", 0], ["FVST", 0.03],
      ["BTC", -0.25], ["ETH", -0.3], ["XRP", -0.2], ["SOL", -0.22],
      ["LINK", -0.18], ["RENDER", -0.12], ["TAO", -0.08], ["XMR", -0.16], ["UNI", -0.2], ["DOGE", -0.14],
    ]),
  },
  {
    id: "hyperinflation",
    name: "Hyperinflation / Fiat Devaluation",
    short: "Fiat shock",
    category: "macro",
    tone: "mixed",
    blurb: "The unit of account fails. Nominal equities reprice; gold and hard-scarcity crypto are bid as monetary refuge.",
    profile: "accelerating",
    shocks: S([
      ["AAPL", 0.15], ["MSFT", 0.08], ["NVDA", 0.1], ["TSLA", 0.2], ["ASML", 0.08],
      ["RHM", 0.06], ["LLY", 0.05], ["MSTR", 0.7], ["CCJ", 0.18],
      ["SPX", 0.05], ["URTH", 0.04], ["QQQ", 0.07], ["TLT", -0.22], ["SMH", 0.08],
      ["ARKK", 0.1], ["BOTZ", 0.06], ["IGLN", 0.42], ["VNQ", 0.08],
      ["PIMIX", -0.1], ["FVST", 0.12],
      ["BTC", 0.65], ["ETH", 0.55], ["XRP", 0.4], ["SOL", 0.5],
      ["LINK", 0.38], ["RENDER", 0.32], ["TAO", 0.3], ["XMR", 0.48], ["UNI", 0.28], ["DOGE", 0.35],
    ]),
  },
  {
    id: "spot_etf",
    name: "Spot ETF Approvals Global",
    short: "Global crypto ETFs",
    category: "sector",
    tone: "bull",
    blurb: "Asian and European regulators open unrestricted crypto ETFs. Institutional pipes fill BTC, ETH and SOL; listed banks stagnate.",
    profile: "delayed",
    shocks: S([
      ["AAPL", 0.02], ["MSFT", 0.02], ["NVDA", 0.03], ["TSLA", 0.03], ["ASML", 0.02],
      ["RHM", 0], ["LLY", 0.01], ["MSTR", 0.48], ["CCJ", 0],
      ["SPX", 0.02], ["URTH", 0.02], ["QQQ", 0.03], ["TLT", -0.01], ["SMH", 0.02],
      ["ARKK", 0.06], ["BOTZ", 0.01], ["IGLN", -0.05], ["VNQ", 0.01],
      ["PIMIX", 0.01], ["FVST", 0.03],
      ["BTC", 0.38], ["ETH", 0.42], ["XRP", 0.22], ["SOL", 0.46],
      ["LINK", 0.28], ["RENDER", 0.16], ["TAO", 0.14], ["XMR", 0.06], ["UNI", 0.2], ["DOGE", 0.24],
    ]),
  },
  {
    id: "green_energy",
    name: "Green Energy Tech Breakthrough",
    short: "Fusion / battery leap",
    category: "sector",
    tone: "bull",
    blurb: "A step-change in generation or storage. Tesla and uranium re-rate; cheap energy is a slow bid under the broad book.",
    profile: "delayed",
    shocks: S([
      ["AAPL", 0.05], ["MSFT", 0.04], ["NVDA", 0.08], ["TSLA", 0.55], ["ASML", 0.06],
      ["RHM", -0.04], ["LLY", 0.02], ["MSTR", 0.04], ["CCJ", 0.42],
      ["SPX", 0.07], ["URTH", 0.08], ["QQQ", 0.06], ["TLT", 0.04], ["SMH", 0.05],
      ["ARKK", 0.16], ["BOTZ", 0.22], ["IGLN", -0.08], ["VNQ", 0.04],
      ["PIMIX", 0.02], ["FVST", 0.04],
      ["BTC", 0.04], ["ETH", 0.03], ["XRP", 0.02], ["SOL", 0.04],
      ["LINK", 0.03], ["RENDER", 0.05], ["TAO", 0.04], ["XMR", 0.01], ["UNI", 0.02], ["DOGE", 0.03],
    ]),
  },
  {
    id: "tax_cuts",
    name: "Global Tax Cuts & Deregulation",
    short: "Tax cuts",
    category: "macro",
    tone: "bull",
    blurb: "Corporate tax cuts and looser antitrust. Buybacks lift mega-cap tech; the S&P follows. Deficits nibble at long bonds.",
    profile: "front",
    shocks: S([
      ["AAPL", 0.18], ["MSFT", 0.16], ["NVDA", 0.14], ["TSLA", 0.12], ["ASML", 0.12],
      ["RHM", 0.06], ["LLY", 0.1], ["MSTR", 0.1], ["CCJ", 0.07],
      ["SPX", 0.14], ["URTH", 0.1], ["QQQ", 0.16], ["TLT", -0.05], ["SMH", 0.13],
      ["ARKK", 0.2], ["BOTZ", 0.1], ["IGLN", 0.02], ["VNQ", 0.08],
      ["PIMIX", 0.02], ["FVST", 0.06],
      ["BTC", 0.08], ["ETH", 0.09], ["XRP", 0.06], ["SOL", 0.1],
      ["LINK", 0.07], ["RENDER", 0.08], ["TAO", 0.07], ["XMR", 0.03], ["UNI", 0.08], ["DOGE", 0.12],
    ]),
  },
  {
    id: "web3",
    name: "Web3 / Metaverse Mainstream Adoption",
    short: "Web3 adoption",
    category: "sector",
    tone: "bull",
    blurb: "A consumer device with native crypto rails reaches daily use. Apple captures hardware; ETH, SOL and LINK take the rails.",
    profile: "gradual",
    shocks: S([
      ["AAPL", 0.24], ["MSFT", 0.08], ["NVDA", 0.12], ["TSLA", 0.06], ["ASML", 0.06],
      ["RHM", 0], ["LLY", 0], ["MSTR", 0.14], ["CCJ", 0],
      ["SPX", 0.04], ["URTH", 0.03], ["QQQ", 0.09], ["TLT", -0.02], ["SMH", 0.08],
      ["ARKK", 0.14], ["BOTZ", 0.06], ["IGLN", -0.02], ["VNQ", 0.01],
      ["PIMIX", 0], ["FVST", 0.03],
      ["BTC", 0.12], ["ETH", 0.38], ["XRP", 0.1], ["SOL", 0.42],
      ["LINK", 0.36], ["RENDER", 0.22], ["TAO", 0.12], ["XMR", 0.04], ["UNI", 0.32], ["DOGE", 0.18],
    ]),
  },
  {
    id: "peace",
    name: "Peace Treaty / End of Major Conflicts",
    short: "Peace treaty",
    category: "geo",
    tone: "bull",
    blurb: "A settlement of major conflicts. World equities and supply chains recover; defense and gold give back the fear premium.",
    profile: "delayed",
    shocks: S([
      ["AAPL", 0.08], ["MSFT", 0.05], ["NVDA", 0.06], ["TSLA", 0.07], ["ASML", 0.1],
      ["RHM", -0.3], ["LLY", 0.03], ["MSTR", -0.06], ["CCJ", -0.04],
      ["SPX", 0.1], ["URTH", 0.16], ["QQQ", 0.08], ["TLT", 0.03], ["SMH", 0.07],
      ["ARKK", 0.08], ["BOTZ", 0.05], ["IGLN", -0.12], ["VNQ", 0.08],
      ["PIMIX", 0.03], ["FVST", 0.04],
      ["BTC", -0.06], ["ETH", -0.04], ["XRP", -0.03], ["SOL", -0.04],
      ["LINK", -0.02], ["RENDER", -0.02], ["TAO", -0.02], ["XMR", -0.08], ["UNI", -0.02], ["DOGE", -0.03],
    ]),
  },
  {
    id: "qe_restart",
    name: "Central Bank QE Restart",
    short: "QE restart",
    category: "macro",
    tone: "bull",
    blurb: "The press runs again to fund sovereigns. Hard assets and duration catch the first bid; meme liquidity follows.",
    profile: "front",
    shocks: S([
      ["AAPL", 0.14], ["MSFT", 0.12], ["NVDA", 0.16], ["TSLA", 0.18], ["ASML", 0.1],
      ["RHM", 0.04], ["LLY", 0.06], ["MSTR", 0.5], ["CCJ", 0.08],
      ["SPX", 0.1], ["URTH", 0.08], ["QQQ", 0.13], ["TLT", 0.22], ["SMH", 0.12],
      ["ARKK", 0.28], ["BOTZ", 0.12], ["IGLN", 0.26], ["VNQ", 0.14],
      ["PIMIX", 0.06], ["FVST", 0.08],
      ["BTC", 0.4], ["ETH", 0.32], ["XRP", 0.24], ["SOL", 0.34],
      ["LINK", 0.22], ["RENDER", 0.26], ["TAO", 0.22], ["XMR", 0.16], ["UNI", 0.2], ["DOGE", 0.48],
    ]),
  },
  {
    id: "cyber_attack",
    name: "Global Cyber Attack on Financial Infrastructure",
    short: "Cyber attack",
    category: "geo",
    tone: "bear",
    blurb: "SWIFT, cards or exchanges go dark for days. Equities panic-sell; gold is bid. Coins gap, then try to reprice as an uncensored rail.",
    profile: "crash_recover",
    shocks: S([
      ["AAPL", -0.14], ["MSFT", -0.16], ["NVDA", -0.12], ["TSLA", -0.14], ["ASML", -0.1],
      ["RHM", 0.06], ["LLY", -0.08], ["MSTR", -0.18], ["CCJ", -0.06],
      ["SPX", -0.18], ["URTH", -0.14], ["QQQ", -0.16], ["TLT", 0.08], ["SMH", -0.12],
      ["ARKK", -0.16], ["BOTZ", -0.1], ["IGLN", 0.24], ["VNQ", -0.1],
      ["PIMIX", -0.05], ["FVST", 0.02],
      ["BTC", -0.12], ["ETH", -0.18], ["XRP", -0.22], ["SOL", -0.2],
      ["LINK", -0.16], ["RENDER", -0.18], ["TAO", -0.14], ["XMR", 0.12], ["UNI", -0.24], ["DOGE", -0.2],
    ]),
  },
  {
    id: "cre_crash",
    name: "Commercial Real Estate Crash",
    short: "CRE crash",
    category: "macro",
    tone: "bear",
    blurb: "Office values gap as regional banks crack. REITs lead the drawdown; fortress tech holds. DeFi and BTC catch a distrust bid.",
    profile: "delayed",
    shocks: S([
      ["AAPL", -0.04], ["MSFT", -0.03], ["NVDA", -0.05], ["TSLA", -0.06], ["ASML", -0.04],
      ["RHM", -0.02], ["LLY", -0.03], ["MSTR", 0.1], ["CCJ", -0.03],
      ["SPX", -0.12], ["URTH", -0.08], ["QQQ", -0.06], ["TLT", 0.06], ["SMH", -0.05],
      ["ARKK", -0.08], ["BOTZ", -0.04], ["IGLN", 0.06], ["VNQ", -0.4],
      ["PIMIX", -0.12], ["FVST", -0.07],
      ["BTC", 0.12], ["ETH", 0.1], ["XRP", 0.04], ["SOL", 0.08],
      ["LINK", 0.1], ["RENDER", 0.04], ["TAO", 0.03], ["XMR", 0.08], ["UNI", 0.2], ["DOGE", 0.06],
    ]),
  },
  {
    id: "ai_reg",
    name: "AI Regulation & Copyright Crackdown",
    short: "AI clampdown",
    category: "sector",
    tone: "bear",
    blurb: "Unlicensed training is barred and fines land on the labs. Microsoft, NVIDIA and the Nasdaq re-rate down; decentralized AI catches the overflow.",
    profile: "front",
    shocks: S([
      ["AAPL", -0.08], ["MSFT", -0.28], ["NVDA", -0.32], ["TSLA", -0.1], ["ASML", -0.14],
      ["RHM", 0], ["LLY", 0.01], ["MSTR", 0.02], ["CCJ", 0],
      ["SPX", -0.08], ["URTH", -0.06], ["QQQ", -0.18], ["TLT", 0.03], ["SMH", -0.22],
      ["ARKK", -0.2], ["BOTZ", -0.16], ["IGLN", 0.02], ["VNQ", 0],
      ["PIMIX", 0.01], ["FVST", -0.02],
      ["BTC", 0.04], ["ETH", 0.06], ["XRP", 0.02], ["SOL", 0.05],
      ["LINK", 0.04], ["RENDER", 0.32], ["TAO", 0.38], ["XMR", 0.03], ["UNI", 0.04], ["DOGE", 0.02],
    ]),
  },
  {
    id: "solar_flare",
    name: "Solar Flare / Global Grid Failure",
    short: "Grid failure",
    category: "geo",
    tone: "bear",
    blurb: "A Carrington-class event darkens grids and the net. Anything that lives on electricity is marked down; gold keeps a bid.",
    profile: "immediate",
    shocks: S([
      ["AAPL", -0.22], ["MSFT", -0.2], ["NVDA", -0.3], ["TSLA", -0.26], ["ASML", -0.18],
      ["RHM", 0.04], ["LLY", -0.12], ["MSTR", -0.5], ["CCJ", -0.08],
      ["SPX", -0.2], ["URTH", -0.18], ["QQQ", -0.24], ["TLT", 0.05], ["SMH", -0.26],
      ["ARKK", -0.28], ["BOTZ", -0.22], ["IGLN", 0.2], ["VNQ", -0.1],
      ["PIMIX", -0.03], ["FVST", 0.04],
      ["BTC", -0.58], ["ETH", -0.62], ["XRP", -0.6], ["SOL", -0.64],
      ["LINK", -0.6], ["RENDER", -0.66], ["TAO", -0.62], ["XMR", -0.52], ["UNI", -0.64], ["DOGE", -0.7],
    ]),
  },
  {
    id: "dedollar",
    name: "De-Dollarization Acceleration",
    short: "De-dollarization",
    category: "macro",
    tone: "bear",
    blurb: "A gold-linked BRICS unit and Treasury dumping hit the US book. Gold and BTC reprice as neutral money; TLT and the S&P give way.",
    profile: "accelerating",
    shocks: S([
      ["AAPL", -0.1], ["MSFT", -0.12], ["NVDA", -0.1], ["TSLA", -0.08], ["ASML", -0.04],
      ["RHM", 0.08], ["LLY", -0.06], ["MSTR", 0.28], ["CCJ", 0.1],
      ["SPX", -0.2], ["URTH", 0.06], ["QQQ", -0.16], ["TLT", -0.24], ["SMH", -0.1],
      ["ARKK", -0.12], ["BOTZ", -0.06], ["IGLN", 0.4], ["VNQ", -0.1],
      ["PIMIX", -0.14], ["FVST", 0.08],
      ["BTC", 0.32], ["ETH", 0.18], ["XRP", 0.12], ["SOL", 0.16],
      ["LINK", 0.14], ["RENDER", 0.08], ["TAO", 0.08], ["XMR", 0.2], ["UNI", 0.1], ["DOGE", 0.08],
    ]),
  },
  {
    id: "tether",
    name: "Tether (USDT) Collapse",
    short: "Tether collapse",
    category: "sector",
    tone: "bear",
    blurb: "The largest dollar stablecoin is shown to be under-reserved. Crypto liquidity vanishes; listed equities print a near-zero beta.",
    profile: "crash_recover",
    shocks: S([
      ["AAPL", 0], ["MSFT", 0], ["NVDA", -0.01], ["TSLA", 0], ["ASML", 0],
      ["RHM", 0], ["LLY", 0], ["MSTR", -0.58], ["CCJ", 0],
      ["SPX", 0], ["URTH", 0], ["QQQ", -0.01], ["TLT", 0.01], ["SMH", 0],
      ["ARKK", -0.02], ["BOTZ", 0], ["IGLN", 0.03], ["VNQ", 0],
      ["PIMIX", 0], ["FVST", 0],
      ["BTC", -0.62], ["ETH", -0.7], ["XRP", -0.76], ["SOL", -0.72],
      ["LINK", -0.66], ["RENDER", -0.7], ["TAO", -0.6], ["XMR", -0.42], ["UNI", -0.74], ["DOGE", -0.8],
    ]),
  },
  {
    id: "hyper_auto",
    name: "Vollautomatisierte Lieferketten",
    short: "Hyper-automation",
    category: "sector",
    tone: "bull",
    blurb: "Autonome Lager und Flotten ersetzen Niedriglohnarbeit. Logistik- und Robotik-Namen ziehen die Marge; Konsumgüter dämpfen.",
    profile: "gradual",
    shocks: S([
      ["AMZN", 0.38], ["BOTZ", 0.42], ["TSLA", 0.18], ["NVDA", 0.14], ["MSFT", 0.08],
      ["AAPL", 0.04], ["ASML", 0.08], ["RHM", 0.02], ["LLY", 0.01], ["MSTR", 0.03], ["CCJ", 0.02],
      ["CRWD", 0.06], ["WMT", -0.08], ["NVO", 0.01], ["LMT", 0.03],
      ["SPX", 0.05], ["URTH", 0.04], ["QQQ", 0.08], ["TLT", -0.02], ["SMH", 0.1],
      ["ARKK", 0.16], ["IGLN", -0.02], ["VNQ", -0.04], ["DBA", -0.03],
      ["PIMIX", 0.01], ["FVST", 0.03],
      ["BTC", 0.04], ["ETH", 0.03], ["XRP", 0.02], ["SOL", 0.04],
      ["LINK", 0.06], ["RENDER", 0.08], ["TAO", 0.1], ["XMR", 0.01], ["UNI", 0.03], ["DOGE", 0.02],
    ]),
  },
  {
    id: "iot_ransom",
    name: "Globale IoT-Ransomware-Welle",
    short: "IoT ransomware",
    category: "geo",
    tone: "bear",
    blurb: "Vernetzte Fabriken und Gebäude gehen dunkel. Hardware und IoT werden abgeschrieben; Cybersecurity und Gold nehmen den Bid.",
    profile: "crash_recover",
    shocks: S([
      ["CRWD", 0.48], ["MSFT", 0.08], ["AMZN", -0.12], ["AAPL", -0.14], ["NVDA", -0.1],
      ["TSLA", -0.16], ["ASML", -0.08], ["RHM", 0.04], ["LLY", -0.03], ["MSTR", -0.06], ["CCJ", -0.04],
      ["WMT", -0.06], ["NVO", -0.02], ["LMT", 0.08],
      ["SPX", -0.1], ["URTH", -0.09], ["QQQ", -0.12], ["TLT", 0.04], ["SMH", -0.1],
      ["ARKK", -0.14], ["BOTZ", -0.22], ["IGLN", 0.1], ["VNQ", -0.08], ["DBA", 0.02],
      ["PIMIX", -0.02], ["FVST", 0.01],
      ["BTC", -0.06], ["ETH", -0.08], ["XRP", -0.08], ["SOL", -0.1],
      ["LINK", -0.12], ["RENDER", -0.08], ["TAO", -0.06], ["XMR", 0.06], ["UNI", -0.1], ["DOGE", -0.08],
    ]),
  },
  {
    id: "rare_earth",
    name: "Seltene-Erden-Embargo",
    short: "Rare-earth embargo",
    category: "geo",
    tone: "bear",
    blurb: "Der Export kritischer Magnete und Oxide stoppt. E-Autos und Hardware gapen; Recycling und heimische Minen re-raten.",
    profile: "immediate",
    shocks: S([
      ["TSLA", -0.32], ["AAPL", -0.18], ["NVDA", -0.12], ["ASML", -0.1], ["AMZN", -0.06],
      ["MSFT", -0.04], ["RHM", 0.06], ["LLY", -0.02], ["MSTR", -0.05], ["CCJ", 0.22],
      ["CRWD", 0.02], ["WMT", -0.04], ["NVO", -0.02], ["LMT", 0.08],
      ["SPX", -0.08], ["URTH", -0.1], ["QQQ", -0.12], ["TLT", 0.03], ["SMH", -0.14],
      ["ARKK", -0.16], ["BOTZ", -0.2], ["IGLN", 0.06], ["VNQ", -0.03], ["DBA", 0.04],
      ["PIMIX", 0], ["FVST", 0.02],
      ["BTC", -0.04], ["ETH", -0.04], ["XRP", -0.03], ["SOL", -0.04],
      ["LINK", -0.03], ["RENDER", -0.05], ["TAO", -0.04], ["XMR", -0.02], ["UNI", -0.03], ["DOGE", -0.04],
    ]),
  },
  {
    id: "ubi",
    name: "Bedingungsloses Grundeinkommen",
    short: "UBI rollout",
    category: "macro",
    tone: "mixed",
    blurb: "Westliche Staaten zahlen ein Basis-Einkommen. Konsumriesen nehmen die erste Welle; Inflation hebt Gold und Bitcoin.",
    profile: "front",
    shocks: S([
      ["WMT", 0.28], ["AMZN", 0.24], ["AAPL", 0.08], ["MSFT", 0.05], ["NVDA", 0.04],
      ["TSLA", 0.06], ["ASML", 0.03], ["RHM", 0.01], ["LLY", 0.06], ["MSTR", 0.22], ["CCJ", 0.04],
      ["CRWD", 0.03], ["NVO", 0.05], ["LMT", 0.01],
      ["SPX", 0.07], ["URTH", 0.06], ["QQQ", 0.06], ["TLT", -0.08], ["SMH", 0.04],
      ["ARKK", 0.08], ["BOTZ", 0.03], ["IGLN", 0.16], ["VNQ", 0.06], ["DBA", 0.12],
      ["PIMIX", -0.04], ["FVST", 0.04],
      ["BTC", 0.22], ["ETH", 0.16], ["XRP", 0.12], ["SOL", 0.18],
      ["LINK", 0.1], ["RENDER", 0.08], ["TAO", 0.08], ["XMR", 0.1], ["UNI", 0.1], ["DOGE", 0.26],
    ]),
  },
  {
    id: "cbdc",
    name: "Zwangseinführung von CBDCs",
    short: "CBDC mandate",
    category: "macro",
    tone: "mixed",
    blurb: "Bargeld endet. Programmierbares Zentralbankgeld macht Teile des Bankbuchs überflüssig; Privacy-Coins und Bitcoin fliehen das Raster.",
    profile: "delayed",
    shocks: S([
      ["AAPL", -0.03], ["MSFT", -0.02], ["NVDA", -0.02], ["TSLA", -0.02], ["ASML", -0.01],
      ["RHM", 0.02], ["LLY", 0], ["MSTR", 0.35], ["CCJ", 0.02],
      ["AMZN", -0.04], ["CRWD", 0.06], ["WMT", -0.02], ["NVO", 0], ["LMT", 0.02],
      ["SPX", -0.06], ["URTH", -0.04], ["QQQ", -0.03], ["TLT", -0.04], ["SMH", -0.02],
      ["ARKK", -0.04], ["BOTZ", -0.02], ["IGLN", 0.08], ["VNQ", -0.03], ["DBA", 0.01],
      ["PIMIX", -0.08], ["FVST", 0.03],
      ["BTC", 0.42], ["ETH", 0.18], ["XRP", -0.12], ["SOL", 0.12],
      ["LINK", 0.08], ["RENDER", 0.04], ["TAO", 0.06], ["XMR", 0.7], ["UNI", 0.22], ["DOGE", 0.08],
    ]),
  },
  {
    id: "debt_default",
    name: "Staatsbankrott einer G7-Nation",
    short: "G7 default",
    category: "macro",
    tone: "bear",
    blurb: "Ein großes westliches Land bedient seine Anleihen nicht. Indizes gapen; Treasuries und Gold saugen das globale Kapital.",
    profile: "immediate",
    shocks: S([
      ["AAPL", -0.22], ["MSFT", -0.2], ["NVDA", -0.26], ["TSLA", -0.28], ["ASML", -0.2],
      ["RHM", 0.06], ["LLY", -0.12], ["MSTR", -0.18], ["CCJ", -0.1],
      ["AMZN", -0.2], ["CRWD", -0.14], ["WMT", -0.1], ["NVO", -0.12], ["LMT", 0.04],
      ["SPX", -0.32], ["URTH", -0.3], ["QQQ", -0.28], ["TLT", 0.16], ["SMH", -0.24],
      ["ARKK", -0.34], ["BOTZ", -0.2], ["IGLN", 0.36], ["VNQ", -0.22], ["DBA", 0.06],
      ["PIMIX", -0.18], ["FVST", 0.04],
      ["BTC", -0.14], ["ETH", -0.2], ["XRP", -0.24], ["SOL", -0.22],
      ["LINK", -0.18], ["RENDER", -0.22], ["TAO", -0.18], ["XMR", 0.04], ["UNI", -0.2], ["DOGE", -0.26],
    ]),
  },
  {
    id: "longevity",
    name: "Longevity-Durchbruch",
    short: "Longevity leap",
    category: "sector",
    tone: "bull",
    blurb: "Eine zugelassene Therapie verlangsamt biologisches Altern. Pharma re-ratet; Pensions- und Versicherungsmathematik bricht.",
    profile: "delayed",
    shocks: S([
      ["LLY", 0.48], ["NVO", 0.42], ["AMZN", 0.04], ["AAPL", 0.03], ["MSFT", 0.04],
      ["NVDA", 0.06], ["TSLA", 0.03], ["ASML", 0.02], ["RHM", -0.02], ["MSTR", 0.02], ["CCJ", 0.01],
      ["CRWD", 0.02], ["WMT", 0.06], ["LMT", -0.04],
      ["SPX", 0.04], ["URTH", 0.03], ["QQQ", 0.05], ["TLT", -0.1], ["SMH", 0.04],
      ["ARKK", 0.12], ["BOTZ", 0.03], ["IGLN", -0.04], ["VNQ", 0.08], ["DBA", 0.02],
      ["PIMIX", -0.08], ["FVST", 0.02],
      ["BTC", 0.03], ["ETH", 0.02], ["XRP", 0.01], ["SOL", 0.02],
      ["LINK", 0.02], ["RENDER", 0.03], ["TAO", 0.04], ["XMR", 0.01], ["UNI", 0.01], ["DOGE", 0.02],
    ]),
  },
  {
    id: "crop_fail",
    name: "Globale Missernten",
    short: "Crop failure",
    category: "macro",
    tone: "bear",
    blurb: "El Niño löscht Weizen- und Sojaernten. Lebensmittelinflation frisst den diskretionären Bid; Agrar-Rohstoffe steigen steil.",
    profile: "front",
    shocks: S([
      ["WMT", -0.06], ["AMZN", -0.08], ["AAPL", -0.1], ["MSFT", -0.06], ["NVDA", -0.08],
      ["TSLA", -0.12], ["ASML", -0.06], ["RHM", 0.02], ["LLY", 0.04], ["MSTR", -0.08], ["CCJ", 0.03],
      ["CRWD", -0.04], ["NVO", 0.06], ["LMT", 0.01],
      ["SPX", -0.08], ["URTH", -0.07], ["QQQ", -0.1], ["TLT", -0.04], ["SMH", -0.08],
      ["ARKK", -0.12], ["BOTZ", -0.06], ["IGLN", 0.08], ["VNQ", -0.04], ["DBA", 0.45],
      ["PIMIX", -0.05], ["FVST", 0.02],
      ["BTC", -0.06], ["ETH", -0.08], ["XRP", -0.08], ["SOL", -0.08],
      ["LINK", -0.06], ["RENDER", -0.08], ["TAO", -0.06], ["XMR", -0.03], ["UNI", -0.07], ["DOGE", -0.1],
    ]),
  },
  {
    id: "labor_gap",
    name: "Demografischer Kollaps",
    short: "Labor shortage",
    category: "macro",
    tone: "mixed",
    blurb: "Der Boomer-Austritt reißt Fachkräfte weg, bevor KI die Lücke füllt. Personalintensive Margen leiden; Automatisierung outperformt.",
    profile: "gradual",
    shocks: S([
      ["BOTZ", 0.32], ["AMZN", 0.14], ["NVDA", 0.12], ["MSFT", 0.1], ["TSLA", 0.1],
      ["AAPL", 0.04], ["ASML", 0.08], ["RHM", -0.06], ["LLY", 0.04], ["MSTR", 0.02], ["CCJ", 0.04],
      ["CRWD", 0.06], ["WMT", -0.12], ["NVO", 0.03], ["LMT", -0.08],
      ["SPX", -0.04], ["URTH", -0.05], ["QQQ", 0.04], ["TLT", -0.03], ["SMH", 0.08],
      ["ARKK", 0.1], ["IGLN", 0.03], ["VNQ", -0.08], ["DBA", 0.04],
      ["PIMIX", -0.02], ["FVST", 0.01],
      ["BTC", 0.03], ["ETH", 0.04], ["XRP", 0.02], ["SOL", 0.04],
      ["LINK", 0.03], ["RENDER", 0.08], ["TAO", 0.12], ["XMR", 0.01], ["UNI", 0.03], ["DOGE", 0.02],
    ]),
  },
  {
    id: "kessler",
    name: "Kessler-Syndrom",
    short: "Kessler syndrome",
    category: "geo",
    tone: "bear",
    blurb: "Weltraumschrott räumt LEO. GPS und Satcom fallen aus; Tech und Telco gapen, Aerospace bekommt den Wiederaufbau-Auftrag.",
    profile: "immediate",
    shocks: S([
      ["LMT", 0.4], ["RHM", 0.18], ["AAPL", -0.16], ["MSFT", -0.12], ["NVDA", -0.1],
      ["TSLA", -0.14], ["ASML", -0.08], ["LLY", -0.04], ["MSTR", -0.1], ["CCJ", -0.02],
      ["AMZN", -0.14], ["CRWD", 0.04], ["WMT", -0.08], ["NVO", -0.04],
      ["SPX", -0.14], ["URTH", -0.12], ["QQQ", -0.16], ["TLT", 0.06], ["SMH", -0.1],
      ["ARKK", -0.18], ["BOTZ", -0.08], ["IGLN", 0.1], ["VNQ", -0.06], ["DBA", 0.04],
      ["PIMIX", -0.03], ["FVST", 0.02],
      ["BTC", -0.12], ["ETH", -0.16], ["XRP", -0.14], ["SOL", -0.16],
      ["LINK", -0.18], ["RENDER", -0.12], ["TAO", -0.1], ["XMR", -0.06], ["UNI", -0.16], ["DOGE", -0.14],
    ]),
  },
  {
    id: "asteroid",
    name: "Kommerzieller Asteroidenabbau",
    short: "Asteroid mining",
    category: "sector",
    tone: "mixed",
    blurb: "Eine Mission landet Platin in Mengen. Edelmetalle verlieren die Knappheit; Bitcoin bleibt die letzte absolut knappe Einheit.",
    profile: "immediate",
    shocks: S([
      ["IGLN", -0.42], ["CCJ", -0.08], ["AAPL", 0.04], ["MSFT", 0.03], ["NVDA", 0.06],
      ["TSLA", 0.08], ["ASML", 0.04], ["RHM", -0.04], ["LLY", 0.01], ["MSTR", 0.28],
      ["AMZN", 0.04], ["CRWD", 0.02], ["WMT", 0.02], ["NVO", 0.01], ["LMT", 0.16],
      ["SPX", 0.03], ["URTH", 0.02], ["QQQ", 0.05], ["TLT", 0.02], ["SMH", 0.04],
      ["ARKK", 0.1], ["BOTZ", 0.06], ["VNQ", 0.02], ["DBA", -0.04],
      ["PIMIX", 0.01], ["FVST", -0.08],
      ["BTC", 0.38], ["ETH", 0.12], ["XRP", 0.06], ["SOL", 0.1],
      ["LINK", 0.08], ["RENDER", 0.06], ["TAO", 0.06], ["XMR", 0.14], ["UNI", 0.06], ["DOGE", 0.08],
    ]),
  },
  {
    id: "algo_war",
    name: "KI-gesteuerter Flash Crash",
    short: "Algo war",
    category: "macro",
    tone: "bear",
    blurb: "AGI-Desks liquidieren einander in Sekunden. Börsen schließen; danach kommt die Klemme auf algorithmisches Trading.",
    profile: "crash_recover",
    shocks: S([
      ["AAPL", -0.28], ["MSFT", -0.26], ["NVDA", -0.34], ["TSLA", -0.36], ["ASML", -0.24],
      ["RHM", -0.1], ["LLY", -0.16], ["MSTR", -0.4], ["CCJ", -0.14],
      ["AMZN", -0.26], ["CRWD", -0.12], ["WMT", -0.14], ["NVO", -0.16], ["LMT", -0.08],
      ["SPX", -0.32], ["URTH", -0.28], ["QQQ", -0.36], ["TLT", 0.12], ["SMH", -0.3],
      ["ARKK", -0.4], ["BOTZ", -0.24], ["IGLN", 0.14], ["VNQ", -0.18], ["DBA", 0.02],
      ["PIMIX", -0.06], ["FVST", -0.04],
      ["BTC", -0.3], ["ETH", -0.34], ["XRP", -0.36], ["SOL", -0.38],
      ["LINK", -0.32], ["RENDER", -0.36], ["TAO", -0.22], ["XMR", -0.16], ["UNI", -0.34], ["DOGE", -0.42],
    ]),
  },
];

const LEGACY_EXTRAS: Partial<Record<ScenarioId, Partial<ShockMap>>> = {
  rate_cut: { AMZN: 0.09, CRWD: 0.08, WMT: 0.05, NVO: 0.06, LMT: 0.02, DBA: 0.02 },
  rate_hike: { AMZN: -0.1, CRWD: -0.12, WMT: -0.05, NVO: -0.06, LMT: 0.01, DBA: -0.03 },
  recession: { AMZN: -0.16, CRWD: -0.14, WMT: -0.08, NVO: -0.1, LMT: -0.06, DBA: -0.04 },
  ai_boom: { AMZN: 0.1, CRWD: 0.08, WMT: 0.02, NVO: 0.02, LMT: 0.02, DBA: 0 },
  taiwan: { AMZN: -0.05, CRWD: -0.03, WMT: -0.02, NVO: -0.01, LMT: 0.04, DBA: 0.01 },
  crypto_ban: { AMZN: -0.01, CRWD: 0, WMT: 0, NVO: 0, LMT: 0, DBA: 0 },
  quantum: { AMZN: 0.04, CRWD: 0.06, WMT: 0.01, NVO: 0.01, LMT: 0.04, DBA: 0 },
  hyperinflation: { AMZN: 0.1, CRWD: 0.04, WMT: 0.12, NVO: 0.05, LMT: 0.04, DBA: 0.14 },
  spot_etf: { AMZN: 0.02, CRWD: 0.01, WMT: 0.01, NVO: 0, LMT: 0, DBA: 0 },
  green_energy: { AMZN: 0.04, CRWD: 0.02, WMT: 0.02, NVO: 0.01, LMT: -0.02, DBA: -0.02 },
  tax_cuts: { AMZN: 0.14, CRWD: 0.1, WMT: 0.08, NVO: 0.08, LMT: 0.04, DBA: 0.02 },
  web3: { AMZN: 0.06, CRWD: 0.03, WMT: 0.02, NVO: 0, LMT: 0, DBA: 0 },
  peace: { AMZN: 0.06, CRWD: -0.04, WMT: 0.04, NVO: 0.03, LMT: -0.22, DBA: 0.02 },
  qe_restart: { AMZN: 0.12, CRWD: 0.08, WMT: 0.08, NVO: 0.05, LMT: 0.03, DBA: 0.06 },
  cyber_attack: { AMZN: -0.14, CRWD: 0.36, WMT: -0.08, NVO: -0.06, LMT: 0.08, DBA: 0.02 },
  cre_crash: { AMZN: -0.03, CRWD: -0.02, WMT: -0.04, NVO: -0.02, LMT: 0, DBA: 0.01 },
  ai_reg: { AMZN: -0.06, CRWD: 0.04, WMT: 0, NVO: 0.01, LMT: 0, DBA: 0 },
  solar_flare: { AMZN: -0.2, CRWD: -0.08, WMT: -0.1, NVO: -0.08, LMT: 0.06, DBA: 0.04 },
  dedollar: { AMZN: -0.1, CRWD: -0.06, WMT: -0.06, NVO: -0.04, LMT: 0.04, DBA: 0.06 },
  tether: { AMZN: 0, CRWD: 0, WMT: 0, NVO: 0, LMT: 0, DBA: 0 },
};

for (const s of SCENARIOS) {
  const extra = LEGACY_EXTRAS[s.id];
  if (extra) Object.assign(s.shocks, extra);
}

export const SCENARIO_BY_ID: Record<ScenarioId, Scenario> = Object.fromEntries(
  SCENARIOS.map((s) => [s.id, s]),
) as Record<ScenarioId, Scenario>;

export const SCENARIO_IDS = SCENARIOS.map((s) => s.id);

export const INTERACTIONS: Interaction[] = [
  {
    id: "cheap-ai",
    kind: "compound",
    pair: ["rate_cut", "ai_boom"],
    label: "Cheap money fuels the AI capex cycle",
    detail: "Lower discount rates duration-extend model and silicon spend. Tech, SMH and QQQ get an extra bid beyond the sum of parts.",
  },
  {
    id: "volcker-recession",
    kind: "compound",
    pair: ["rate_hike", "recession"],
    label: "Tight policy into contracting demand",
    detail: "A hike into a recession compounds the earnings and multiple hit. High-beta names and ARKK gap further.",
  },
  {
    id: "liq-vs-cashflow",
    kind: "conflict",
    pair: ["rate_cut", "recession"],
    label: "Liquidity eases as cash-flows shrink",
    detail: "The cut supports valuations while the recession cuts earnings. Net path is muted and the cone widens.",
  },
  {
    id: "ease-into-fiat",
    kind: "conflict",
    pair: ["rate_cut", "hyperinflation"],
    label: "Easing into a fiat shock",
    detail: "Nominal risk assets get mixed signals. Gold and crypto inherit more of the devaluation bid; the cut’s equity boost halves.",
  },
  {
    id: "stagflation",
    kind: "compound",
    pair: ["rate_hike", "hyperinflation"],
    label: "Stagflationary squeeze",
    detail: "A Volcker-style hike into sticky prices crushes duration. BTC and gold still hedge the unit-of-account failure, but less cleanly.",
  },
  {
    id: "wafers-vs-models",
    kind: "conflict",
    pair: ["taiwan", "ai_boom"],
    label: "Model demand without wafers",
    detail: "AI spend wants more silicon than a Taiwan shock can ship. NVIDIA and ASML are capped; software holds up better than hardware.",
  },
  {
    id: "supply-into-hole",
    kind: "compound",
    pair: ["taiwan", "recession"],
    label: "Supply shock into a demand hole",
    detail: "A fab crisis in a recession is doubly deflationary for hardware and risk-off for everything else.",
  },
  {
    id: "outlawed-hedge",
    kind: "conflict",
    pair: ["crypto_ban", "hyperinflation"],
    label: "The hedge is outlawed as the unit fails",
    detail: "Fiat devaluation wants a crypto bid the ban forbids. Coins settle in a wide, residual underground range. Gold takes the flow.",
  },
  {
    id: "liq-out-legal-out",
    kind: "compound",
    pair: ["crypto_ban", "rate_hike"],
    label: "Liquidity out, legal out",
    detail: "A hike and a ban drain both the speculative bid and the on-ramp. Crypto and MSTR drawdowns stack.",
  },
  {
    id: "protocol-plus-ban",
    kind: "compound",
    pair: ["quantum", "crypto_ban"],
    label: "Protocol risk plus prohibition",
    detail: "A cryptographic scare and a legal ban are the same trade for coins — both empty the bid.",
  },
  {
    id: "second-s-curve",
    kind: "compound",
    pair: ["quantum", "ai_boom"],
    label: "A second compute S-curve",
    detail: "Quantum and AI spend land on the same pick-and-shovel complex. Microsoft, NVIDIA and SMH compound.",
  },
  {
    id: "algos-need-fabs",
    kind: "conflict",
    pair: ["taiwan", "quantum"],
    label: "Breakthroughs still need leading-edge fabs",
    detail: "A quantum milestone does not ship without TSMC-class process. ASML and NVIDIA upside is bound by the island.",
  },
  {
    id: "etf-plus-qe",
    kind: "compound",
    pair: ["spot_etf", "qe_restart"],
    label: "Pipes open into a liquidity wave",
    detail: "New ETF on-ramps meet QE. BTC, ETH, SOL and MSTR take a larger bid than either event alone.",
  },
  {
    id: "etf-vs-ban",
    kind: "conflict",
    pair: ["spot_etf", "crypto_ban"],
    label: "A product without a legal market",
    detail: "Approvals are worthless if the underlying is prohibited. The ETF bid and the ban cancel; the cone is the story.",
  },
  {
    id: "etf-vs-tether",
    kind: "conflict",
    pair: ["spot_etf", "tether"],
    label: "Institutional pipes into a liquidity vacuum",
    detail: "ETF demand wants coins the Tether collapse cannot price. Majors gap; listed names stay almost still.",
  },
  {
    id: "tax-plus-cut",
    kind: "compound",
    pair: ["tax_cuts", "rate_cut"],
    label: "Fiscal and monetary easing together",
    detail: "Buybacks and a lower discount rate are the same trade for mega-cap tech. The S&P and QQQ compound.",
  },
  {
    id: "qe-vs-hike",
    kind: "conflict",
    pair: ["qe_restart", "rate_hike"],
    label: "The press versus the hike",
    detail: "One desk is injecting duration, the other is draining it. Gold and BTC keep more of the bid than TLT.",
  },
  {
    id: "qe-plus-fiat",
    kind: "compound",
    pair: ["qe_restart", "hyperinflation"],
    label: "Monetisation as the unit fails",
    detail: "QE into a fiat shock is the gold-and-bitcoin tape. Duration is offered; IGLN and BTC take the flow.",
  },
  {
    id: "web3-plus-etf",
    kind: "compound",
    pair: ["web3", "spot_etf"],
    label: "Consumer rails plus institutional pipes",
    detail: "A daily-use device and a global ETF complex feed the same coins. ETH, SOL and LINK pull away from BTC.",
  },
  {
    id: "web3-vs-ban",
    kind: "conflict",
    pair: ["web3", "crypto_ban"],
    label: "A native-crypto device in a banned market",
    detail: "Hardware can ship; the rails cannot. Apple keeps some of the device bid; coins are capped.",
  },
  {
    id: "ai-vs-clamp",
    kind: "conflict",
    pair: ["ai_boom", "ai_reg"],
    label: "Capex cycle under a copyright bar",
    detail: "The boom wants more models than a clampdown will license. NVIDIA and MSFT are capped; TAO and RENDER inherit the overflow.",
  },
  {
    id: "taiwan-plus-clamp",
    kind: "compound",
    pair: ["taiwan", "ai_reg"],
    label: "No wafers, no license",
    detail: "A fab shock and an AI fine are the same trade for NVIDIA and SMH — both empty the multiple.",
  },
  {
    id: "cre-plus-hike",
    kind: "compound",
    pair: ["cre_crash", "rate_hike"],
    label: "Offices into tighter money",
    detail: "A hike into a CRE gap is how regional-bank stress becomes a REIT event. VNQ and PIMIX stack the loss.",
  },
  {
    id: "cre-vs-cut",
    kind: "conflict",
    pair: ["cre_crash", "rate_cut"],
    label: "A cut that arrives after the vacancy",
    detail: "Cheaper money supports cap rates the occupancy shock is still cutting. VNQ’s path is wide, not clean.",
  },
  {
    id: "peace-vs-taiwan",
    kind: "conflict",
    pair: ["peace", "taiwan"],
    label: "A settlement that is not this island",
    detail: "Broader peace does not restock TSMC. World equities recover; ASML and NVIDIA stay bound to the strait.",
  },
  {
    id: "flare-plus-tether",
    kind: "compound",
    pair: ["solar_flare", "tether"],
    label: "The rail and the dollar-peg both fail",
    detail: "A dark grid and a broken stablecoin are the same trade for coins. Gold is the residual store.",
  },
  {
    id: "dedollar-plus-fiat",
    kind: "compound",
    pair: ["dedollar", "hyperinflation"],
    label: "The reserve currency and the unit fail together",
    detail: "Treasury dumping into a fiat shock is the IGLN tape. BTC tags along as neutral money; TLT is offered.",
  },
  {
    id: "green-vs-flare",
    kind: "conflict",
    pair: ["green_energy", "solar_flare"],
    label: "A breakthrough that cannot be plugged in",
    detail: "Cheap energy is a 2028 story; a dark grid is a this-week story. Tesla’s leap is postponed, not cancelled.",
  },
  {
    id: "ban-plus-tether",
    kind: "compound",
    pair: ["crypto_ban", "tether"],
    label: "Legal out, dollar-peg out",
    detail: "A ban and a USDT gap empty both the on-ramp and the quote. Coins print the floor; equities barely move.",
  },
  {
    id: "robots-fill-gap",
    kind: "compound",
    pair: ["hyper_auto", "labor_gap"],
    label: "Robots into an empty shop floor",
    detail: "A labor hole and a warehouse that no longer needs labor are the same trade. BOTZ and AMZN compound.",
  },
  {
    id: "robots-need-oxides",
    kind: "conflict",
    pair: ["hyper_auto", "rare_earth"],
    label: "Automation without magnets",
    detail: "The fleet wants rare earths the embargo will not ship. Tesla and BOTZ are capped; the margin story waits.",
  },
  {
    id: "iot-plus-cyber",
    kind: "compound",
    pair: ["iot_ransom", "cyber_attack"],
    label: "The plant and the rail both go dark",
    detail: "A factory ransomware wave and a payments outage are one infra event. CRWD takes both bids; hardware stacks the loss.",
  },
  {
    id: "auto-vs-ransom",
    kind: "conflict",
    pair: ["hyper_auto", "iot_ransom"],
    label: "A dark plant cannot compound margins",
    detail: "Hyper-automation lives on the same IoT the ransom wave owns. AMZN and BOTZ give the automation bid back.",
  },
  {
    id: "oxides-vs-fusion",
    kind: "conflict",
    pair: ["rare_earth", "green_energy"],
    label: "A battery leap without the oxide",
    detail: "Cheap energy still needs magnets. Tesla’s green bid is bound by the embargo.",
  },
  {
    id: "ubi-plus-print",
    kind: "compound",
    pair: ["ubi", "qe_restart"],
    label: "A cheque and a press",
    detail: "UBI funded into QE is the consumption-and-hard-asset tape. WMT, AMZN, gold and BTC compound.",
  },
  {
    id: "ubi-into-fiat",
    kind: "compound",
    pair: ["ubi", "hyperinflation"],
    label: "Cheques into a failing unit",
    detail: "Printed income into a fiat shock is gold and bitcoin, not duration. WMT still clears the first spend.",
  },
  {
    id: "ubi-vs-crops",
    kind: "conflict",
    pair: ["ubi", "crop_fail"],
    label: "Liquidity that only buys calories",
    detail: "The cheque arrives as the harvest fails. DBA takes the flow; discretionary tech is offered.",
  },
  {
    id: "cbdc-vs-ban",
    kind: "conflict",
    pair: ["cbdc", "crypto_ban"],
    label: "The exit is outlawed as cash dies",
    detail: "A CBDC mandate wants a privacy bid the ban forbids. XMR and BTC settle in a wide residual range.",
  },
  {
    id: "g7-plus-dedollar",
    kind: "compound",
    pair: ["debt_default", "dedollar"],
    label: "A default into a reserve-currency run",
    detail: "A G7 miss and a BRICS unit are the same gold tape. TLT is no longer a clean refuge if the issuer is the story.",
  },
  {
    id: "g7-plus-fiat",
    kind: "compound",
    pair: ["debt_default", "hyperinflation"],
    label: "Insolvency as the unit fails",
    detail: "A default into devaluation empties equities. IGLN takes the only clean bid.",
  },
  {
    id: "life-vs-labor",
    kind: "conflict",
    pair: ["longevity", "labor_gap"],
    label: "Longer lives, fewer hands",
    detail: "A longevity leap keeps some workers in the book the demographic hole is still emptying. Pharma holds; WMT does not.",
  },
  {
    id: "crops-plus-fiat",
    kind: "compound",
    pair: ["crop_fail", "hyperinflation"],
    label: "Calories into a failing unit",
    detail: "Food inflation and a fiat shock are one price-level event. DBA and gold compound; tech is collateral.",
  },
  {
    id: "labor-plus-ai",
    kind: "compound",
    pair: ["labor_gap", "ai_boom"],
    label: "Models into a missing cohort",
    detail: "The AI cycle is the only substitute for the retiring cohort. NVDA, BOTZ and AMZN pull away from labor-heavy names.",
  },
  {
    id: "orbit-plus-cyber",
    kind: "compound",
    pair: ["kessler", "cyber_attack"],
    label: "No clock, no rail",
    detail: "GPS debris and a payments outage are the same operational hole. LMT rebuilds; listed tech stacks the downtime.",
  },
  {
    id: "rocks-vs-gold",
    kind: "conflict",
    pair: ["asteroid", "hyperinflation"],
    label: "The hedge is no longer scarce",
    detail: "A fiat shock wants gold the asteroid has just made common. BTC inherits the store-of-value bid; IGLN is offered.",
  },
  {
    id: "rocks-vs-dedollar",
    kind: "conflict",
    pair: ["asteroid", "dedollar"],
    label: "A reserve-currency run without a metal",
    detail: "De-dollarization wants gold the mine in orbit has flooded. Bitcoin is the residual neutral money.",
  },
  {
    id: "flash-plus-clamp",
    kind: "compound",
    pair: ["algo_war", "ai_reg"],
    label: "The bot war meets the copyright bar",
    detail: "A flash crash and an AI fine are the same multiple for listed model names. NVIDIA and the Nasdaq stack.",
  },
  {
    id: "flash-plus-cyber",
    kind: "compound",
    pair: ["algo_war", "cyber_attack"],
    label: "Liquidation into a dark rail",
    detail: "An algo war into a payments outage is how a 40-point print becomes a close. Gold and TLT take the only bid.",
  },
];

export type Preset = {
  id: string;
  name: string;
  desc: string;
  set: Partial<Record<ScenarioId, number>>;
};

export const PRESETS: Preset[] = [
  { id: "soft_landing", name: "Soft landing", desc: "A clean 50bp cut", set: { rate_cut: 80 } },
  { id: "ai_supercycle", name: "AI supercycle", desc: "Cheap money plus robotics", set: { rate_cut: 70, ai_boom: 100 } },
  { id: "stagflation", name: "Stagflation", desc: "Hike into a fiat shock", set: { rate_hike: 80, hyperinflation: 70 } },
  { id: "chip_shock", name: "Chip shock", desc: "Taiwan into AI demand", set: { taiwan: 100, ai_boom: 80 } },
  { id: "crypto_winter", name: "Crypto winter", desc: "Ban plus a hike", set: { crypto_ban: 100, rate_hike: 70 } },
  { id: "fiat_break", name: "Fiat break", desc: "Devaluation with residual easing", set: { hyperinflation: 90, rate_cut: 60 } },
  { id: "hard_landing", name: "Hard landing", desc: "Recession plus a hike", set: { recession: 90, rate_hike: 70 } },
  { id: "quantum_era", name: "Quantum era", desc: "Compute on an AI base", set: { quantum: 85, ai_boom: 70 } },
  { id: "etf_wave", name: "ETF wave", desc: "Global crypto ETFs", set: { spot_etf: 100 } },
  { id: "fusion_age", name: "Fusion age", desc: "Energy breakthrough", set: { green_energy: 100 } },
  { id: "liquidity", name: "Liquidity", desc: "QE plus tax cuts", set: { qe_restart: 90, tax_cuts: 70 } },
  { id: "web3_wave", name: "Web3 wave", desc: "Adoption plus ETFs", set: { web3: 90, spot_etf: 60 } },
  { id: "ai_clamp", name: "AI clamp", desc: "Boom under a copyright bar", set: { ai_boom: 70, ai_reg: 100 } },
  { id: "office_bust", name: "Office bust", desc: "CRE plus a hike", set: { cre_crash: 90, rate_hike: 70 } },
  { id: "dollar_break", name: "Dollar break", desc: "De-dollar plus fiat", set: { dedollar: 90, hyperinflation: 60 } },
  { id: "usdt_gap", name: "USDT gap", desc: "Tether collapse", set: { tether: 100 } },
  { id: "blackout", name: "Blackout", desc: "Grid failure", set: { solar_flare: 100 } },
  { id: "pax", name: "Pax", desc: "Peace treaty", set: { peace: 100 } },
  { id: "auto_age", name: "Auto age", desc: "Hyper-automation", set: { hyper_auto: 100 } },
  { id: "earth_lock", name: "Earth lock", desc: "Rare earths into green demand", set: { rare_earth: 100, green_energy: 70 } },
  { id: "ubi_wave", name: "UBI wave", desc: "Basic income plus QE", set: { ubi: 90, qe_restart: 60 } },
  { id: "cashless", name: "Cashless", desc: "CBDC mandate", set: { cbdc: 100 } },
  { id: "g7_break", name: "G7 break", desc: "Sovereign default", set: { debt_default: 100 } },
  { id: "long_life", name: "Long life", desc: "Longevity leap", set: { longevity: 100 } },
  { id: "famine", name: "Famine", desc: "Crop failure", set: { crop_fail: 100 } },
  { id: "hands", name: "Hands", desc: "Labor hole plus AI", set: { labor_gap: 90, ai_boom: 70 } },
  { id: "debris", name: "Debris", desc: "Kessler syndrome", set: { kessler: 100 } },
  { id: "platinum", name: "Platinum rain", desc: "Asteroid mining", set: { asteroid: 100 } },
  { id: "flash", name: "Flash", desc: "Algo war", set: { algo_war: 100 } },
];

export const DEFAULT_WEIGHTS: Record<ScenarioId, number> = Object.fromEntries(
  SCENARIO_IDS.map((id) => [id, 100]),
) as Record<ScenarioId, number>;

export const DEFAULT_VISIBLE: AssetId[] = ["AAPL", "MSFT", "NVDA", "TSLA", "BTC"];

export const CLASS_LABEL: Record<Asset["class"], string> = {
  equity: "Equity",
  etf: "ETF",
  fund: "Fund",
  crypto: "Crypto",
};
